(function(g){var window=this;'use strict';var bRa=function(a,b){return g.Tb(a,b)},cRa=function(a,b){b=b instanceof g.Lc?b:g.Rc(b,/^data:image\//i.test(b));
a.src=g.Mc(b)},dRa=function(a){if(a instanceof g.ci)return a;
if("function"==typeof a.Kg)return a.Kg(!1);if(g.Ka(a)){var b=0,c=new g.ci;c.i=function(){for(;;){if(b>=a.length)throw g.ii;if(b in a)return a[b++];b++}};
c.next=c.i.bind(c);return c}throw Error("Not implemented");},eRa=function(a,b,c){if(g.Ka(a))try{g.Db(a,b,c)}catch(d){if(d!==g.ii)throw d;
}else{a=dRa(a);try{for(;;)b.call(c,a.i(),void 0,a)}catch(d){if(d!==g.ii)throw d;}}},N6=function(a){g.gk(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Pa()).toString(36));
return a},O6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.lk(a.u,b,c)},fRa=function(a,b){var c=[];
eRa(b,function(d){try{var e=g.tr.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.sr(e)&&c.push(d)},a);
return c},gRa=function(a,b){fRa(a,b).forEach(function(c){g.tr.prototype.remove.call(this,c)},a)},hRa=function(a){if(a.ea){if(a.ea.locationOverrideToken)return{locationOverrideToken:a.ea.locationOverrideToken};
if(null!=a.ea.latitudeE7&&null!=a.ea.longitudeE7)return{latitudeE7:a.ea.latitudeE7,longitudeE7:a.ea.longitudeE7}}return null},iRa=function(a,b){g.ib(a,b)||a.push(b)},P6=function(a){var b=0,c;
for(c in a)b++;return b},jRa=function(a){try{return g.C.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Q6=function(a){if(g.C.JSON)try{return g.C.JSON.parse(a)}catch(b){}return jRa(a)},kRa=function(a,b,c,d){var e=new g.Yj(null,void 0);
a&&g.Zj(e,a);b&&g.ak(e,b);c&&g.bk(e,c);d&&(e.K=d);return e},R6=function(a,b){g.av[a]=!0;
var c=g.Zu();c&&c.publish.apply(c,arguments);g.av[a]=!1},S6=function(a){this.name=this.id="";
this.clientName="UNKNOWN_INTERFACE";this.app="";this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.ji;this.model=this.brand="";this.year=0;this.chipset=this.osVersion=this.os="";this.mdxDialServerType="MDX_DIAL_SERVER_TYPE_UNKNOWN";a&&(this.id=a.id||a.name,this.name=a.name,this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=
a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",lRa(this,a.capabilities||""),mRa(this,a.experiments||""),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN",a=a.deviceInfo)&&(a=JSON.parse(a),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",
this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN")},lRa=function(a,b){a.capabilities.clear();
g.No(b.split(","),g.Oa(bRa,nRa)).forEach(function(c){a.capabilities.add(c)})},mRa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},T6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},U6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},oRa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},pRa=function(a){return new T6(a)},qRa=function(a){return Array.isArray(a)?g.Bm(a,pRa):[]},V6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},W6=function(a){return Array.isArray(a)?"["+g.Bm(a,V6).join(",")+"]":"null"},X6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},rRa=function(a){return g.Bm(a,function(b){return{key:b.id,
name:b.name}})},Y6=function(a,b){return g.eb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},Z6=function(a,b){return g.eb(a,function(c){return U6(c,b)})},sRa=function(){var a=(0,g.Rz)();
a&&gRa(a,a.i.Kg(!0))},$6=function(){var a=g.Uz("yt-remote-connected-devices")||[];
g.Ab(a);return a},tRa=function(a){if(g.jb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Bm(a,function(d,e){return 0==e?d:d.substring(c.length)})},uRa=function(a){g.Tz("yt-remote-connected-devices",a,86400)},b7=function(){if(a7)return a7;
var a=g.Uz("yt-remote-device-id");a||(a=X6(),g.Tz("yt-remote-device-id",a,31536E3));for(var b=$6(),c=1,d=a;g.ib(b,d);)c++,d=a+"#"+c;return a7=d},c7=function(){var a=$6(),b=b7();
g.ib(a,b);g.Xz()&&g.Cb(a,b);a=tRa(a);if(g.jb(a))try{g.Kt("remote_sid")}catch(c){}else try{g.It("remote_sid",a.join(","),-1)}catch(c){}},vRa=function(){return g.Uz("yt-remote-session-browser-channel")},wRa=function(){return g.Uz("yt-remote-local-screens")||[]},xRa=function(){g.Tz("yt-remote-lounge-token-expiration",!0,86400)},yRa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Bm(wRa(),function(d){return d.loungeToken}),c=g.Bm(a,function(d){return d.loungeToken});
g.Cm(c,function(d){return!g.ib(b,d)})&&xRa();
g.Tz("yt-remote-local-screens",a,31536E3)},zRa=function(a,b){g.Tz("yt-remote-session-browser-channel",a);
g.Tz("yt-remote-session-screen-id",b);a=$6();b=b7();g.ib(a,b)||a.push(b);uRa(a);c7()},d7=function(a){a||(g.Wz("yt-remote-session-screen-id"),g.Wz("yt-remote-session-video-id"));
c7();a=$6();g.ob(a,b7());uRa(a)},ARa=function(){if(!e7){var a=g.Dr();
a&&(e7=new g.nr(a))}},BRa=function(){ARa();
return e7?!!e7.get("yt-remote-use-staging-server"):!1},f7=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},CRa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},DRa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},g7=function(a){a.length?ERa(a.shift(),function(){g7(a)}):h7()},FRa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},ERa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.$k(d,g.cr(a));(document.head||document.documentElement).appendChild(d)},GRa=function(){var a=f7(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},h7=function(){var a=DRa();
a&&a(!1,"No cast extension found")},i7=function(){if(HRa){var a=2,b=DRa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;ERa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",h7,c)}},IRa=function(){i7();
var a=GRa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");g7(a)},KRa=function(){i7();
var a=GRa();a.push.apply(a,g.v(JRa.map(FRa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");g7(a)},j7=function(a,b,c){g.I.call(this);
this.J=null!=c?(0,g.D)(a,c):a;this.Rf=b;this.D=(0,g.D)(this.tP,this);this.i=!1;this.u=0;this.B=this.Lb=null;this.C=[]},k7=function(a,b,c){g.I.call(this);
this.C=null!=c?a.bind(c):a;this.Rf=b;this.B=null;this.i=!1;this.u=0;this.Lb=null},l7=function(a){a.Lb=g.vh(function(){a.Lb=null;
a.i&&!a.u&&(a.i=!1,l7(a))},a.Rf);
var b=a.B;a.B=null;a.C.apply(null,b)},m7=function(){},n7=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.C.setTimeout(function(){a()},b)},p7=function(a){o7.dispatchEvent(new LRa(o7,a))},LRa=function(a,b){g.xf.call(this,"statevent",a);
this.stat=b},q7=function(a,b,c,d){this.i=a;
this.B=b;this.N=c;this.K=d||1;this.u=45E3;this.C=new g.mk(this);this.J=new g.uh;this.J.setInterval(250)},NRa=function(a,b,c){a.Zs=1;
a.Pm=N6(b.clone());a.jq=c;a.D=!0;MRa(a,null)},r7=function(a,b,c,d,e){a.Zs=1;
a.Pm=N6(b.clone());a.jq=null;a.D=c;e&&(a.CM=!1);MRa(a,d)},MRa=function(a,b){a.Ns=Date.now();
s7(a);a.po=a.Pm.clone();O6(a.po,"t",a.K);a.LA=0;a.Jf=a.i.AC(a.i.Nw()?b:null);0<a.AB&&(a.Yz=new k7((0,g.D)(a.DN,a,a.Jf),a.AB));a.C.Sa(a.Jf,"readystatechange",a.uP);b=a.Oo?g.$b(a.Oo):{};a.jq?(a.IA="POST",b["Content-Type"]="application/x-www-form-urlencoded",a.Jf.send(a.po,a.IA,a.jq,b)):(a.IA="GET",a.CM&&!g.xg&&(b.Connection="close"),a.Jf.send(a.po,a.IA,null,b));a.i.vj(1)},PRa=function(a,b){var c=a.LA,d=b.indexOf("\n",c);
if(-1==d)return t7;c=Number(b.substring(c,d));if(isNaN(c))return ORa;d+=1;if(d+c>b.length)return t7;b=b.substr(d,c);a.LA=d+c;return b},RRa=function(a,b){a.Ns=Date.now();
s7(a);var c=b?window.location.hostname:"";a.po=a.Pm.clone();g.gk(a.po,"DOMAIN",c);g.gk(a.po,"t",a.K);try{a.Lj=new ActiveXObject("htmlfile")}catch(m){u7(a);a.Jm=7;p7(22);v7(a);return}var d="<html><body>";if(b){var e="";for(b=0;b<c.length;b++){var f=c.charAt(b);if("<"==f)f=e+"\\x3c";else if(">"==f)f=e+"\\x3e";else{if(f in w7)f=w7[f];else if(f in QRa)f=w7[f]=QRa[f];else{var h=f.charCodeAt(0);if(31<h&&127>h)var l=f;else{if(256>h){if(l="\\x",16>h||256<h)l+="0"}else l="\\u",4096>h&&(l+="0");l+=h.toString(16).toUpperCase()}f=
w7[f]=l}f=e+f}e=f}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.md(g.nc("b/12014412"),d);a.Lj.open();a.Lj.write(g.hd(c));a.Lj.close();a.Lj.parentWindow.m=(0,g.D)(a.EV,a);a.Lj.parentWindow.d=(0,g.D)(a.OL,a,!0);a.Lj.parentWindow.rpcClose=(0,g.D)(a.OL,a,!1);c=a.Lj.createElement("DIV");a.Lj.parentWindow.document.body.appendChild(c);d=g.Qc(a.po.toString());d=g.vd(g.Mc(d));d=g.md(g.nc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.od(c,d);a.i.vj(1)},s7=function(a){a.ZF=Date.now()+
a.u;
SRa(a,a.u)},SRa=function(a,b){if(null!=a.wt)throw Error("WatchDog timer not null");
a.wt=n7((0,g.D)(a.LV,a),b)},x7=function(a){a.wt&&(g.C.clearTimeout(a.wt),a.wt=null)},v7=function(a){a.i.jf()||a.gp||a.i.tx(a)},u7=function(a){x7(a);
g.uf(a.Yz);a.Yz=null;a.J.stop();g.ok(a.C);if(a.Jf){var b=a.Jf;a.Jf=null;b.abort();b.dispose()}a.Lj&&(a.Lj=null)},y7=function(a,b){try{a.i.HL(a,b),a.i.vj(4)}catch(c){}},URa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;TRa(a,b,function(h){h?c(!0):g.C.setTimeout(function(){URa(a,b,c,d,f)},f)})}},TRa=function(a,b,c){var d=new Image;
d.onload=function(){try{z7(d),c(!0)}catch(e){}};
d.onerror=function(){try{z7(d),c(!1)}catch(e){}};
d.onabort=function(){try{z7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{z7(d),c(!1)}catch(e){}};
g.C.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
cRa(d,a)},z7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},VRa=function(a){this.i=a;
this.u=new m7},WRa=function(a){var b=A7(a.i,a.xu,"/mail/images/cleardot.gif");
N6(b);URa(b.toString(),5E3,(0,g.D)(a.pQ,a),3,2E3);a.vj(1)},C7=function(a){var b=a.i.V;
if(null!=b)p7(5),b?(p7(11),B7(a.i,a,!1)):(p7(12),B7(a.i,a,!0));else if(a.nh=new q7(a,void 0,void 0,void 0),a.nh.Oo=a.BB,b=a.i,b=A7(b,b.Nw()?a.Tt:null,a.CB),p7(5),!g.ke||g.ce(10))O6(b,"TYPE","xmlhttp"),r7(a.nh,b,!1,a.Tt,!1);else{O6(b,"TYPE","html");var c=a.nh;a=!!a.Tt;c.Zs=3;c.Pm=N6(b.clone());RRa(c,a)}},D7=function(a,b,c){this.i=1;
this.u=[];this.C=[];this.D=new m7;this.N=a||null;this.V=null!=b?b:null;this.J=c||!1},XRa=function(a,b){this.i=a;
this.map=b;this.context=null},YRa=function(a,b,c,d){g.xf.call(this,"timingevent",a);
this.size=b;this.Fw=d},ZRa=function(a){g.xf.call(this,"serverreachability",a)},bSa=function(a){$Ra(a);
if(3==a.i){var b=a.Vv++,c=a.dy.clone();g.gk(c,"SID",a.B);g.gk(c,"RID",b);g.gk(c,"TYPE","terminate");E7(a,c);b=new q7(a,a.B,b,void 0);b.Zs=2;b.Pm=N6(c.clone());cRa(new Image,b.Pm.toString());b.Ns=Date.now();s7(b)}aSa(a)},cSa=function(a){a.PQ(1,0);
a.dy=A7(a,null,a.DB);F7(a)},$Ra=function(a){a.Tm&&(a.Tm.abort(),a.Tm=null);
a.De&&(a.De.cancel(),a.De=null);a.zl&&(g.C.clearTimeout(a.zl),a.zl=null);G7(a);a.Vg&&(a.Vg.cancel(),a.Vg=null);a.hn&&(g.C.clearTimeout(a.hn),a.hn=null)},dSa=function(a,b){if(0==a.i)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new XRa(a.vS++,b));2!=a.i&&3!=a.i||F7(a)},eSa=function(a){var b=0;
a.De&&b++;a.Vg&&b++;return b},F7=function(a){a.Vg||a.hn||(a.hn=n7((0,g.D)(a.ML,a),0),a.Jr=0)},gSa=function(a,b){if(1==a.i){if(!b){a.Vv=Math.floor(1E5*Math.random());
b=a.Vv++;var c=new q7(a,"",b,void 0);c.Oo=a.Xj;var d=H7(a),e=a.dy.clone();g.gk(e,"RID",b);g.gk(e,"CVER","1");E7(a,e);NRa(c,e,d);a.Vg=c;a.i=2}}else 3==a.i&&(b?fSa(a,b):0==a.u.length||a.Vg||fSa(a))},fSa=function(a,b){if(b)if(6<a.hp){a.u=a.C.concat(a.u);
a.C.length=0;var c=a.Vv-1;b=H7(a)}else c=b.N,b=b.jq;else c=a.Vv++,b=H7(a);var d=a.dy.clone();g.gk(d,"SID",a.B);g.gk(d,"RID",c);g.gk(d,"AID",a.ls);E7(a,d);c=new q7(a,a.B,c,a.Jr+1);c.Oo=a.Xj;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Vg=c;NRa(c,d,b)},E7=function(a,b){a.Kf&&(a=a.Kf.jJ())&&g.Fb(a,function(c,d){g.gk(b,d,c)})},H7=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.hp&&0<b){var d=a.u[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={Nq:e.Nq},f++){e.Nq=a.u[f].i;var h=a.u[f].map;e.Nq=6>=a.hp?f:e.Nq-d;try{g.Fb(h,function(l){return function(m,n){c.push("req"+l.Nq+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.Nq+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.u.splice(0,b));
return c.join("&")},hSa=function(a){a.De||a.zl||(a.K=1,a.zl=n7((0,g.D)(a.LL,a),0),a.rr=0)},I7=function(a){if(a.De||a.zl||3<=a.rr)return!1;
a.K++;a.zl=n7((0,g.D)(a.LL,a),iSa(a,a.rr));a.rr++;return!0},B7=function(a,b,c){a.GA=c;
a.Yj=b.bl;a.J||cSa(a)},G7=function(a){null!=a.qp&&(g.C.clearTimeout(a.qp),a.qp=null)},iSa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},J7=function(a,b){if(2==b||9==b){var c=null;
a.Kf&&(c=null);var d=(0,g.D)(a.MW,a);c||(c=new g.Yj("//www.google.com/images/cleardot.gif"),N6(c));TRa(c.toString(),1E4,d)}else p7(2);jSa(a,b)},jSa=function(a,b){a.i=0;
a.Kf&&a.Kf.vI(b);aSa(a);$Ra(a)},aSa=function(a){a.i=0;
a.Yj=-1;if(a.Kf)if(0==a.C.length&&0==a.u.length)a.Kf.nC();else{g.sb(a.C);var b=g.sb(a.u);a.C.length=0;a.u.length=0;a.Kf.nC(b)}},A7=function(a,b,c){var d=g.hk(c);
if(""!=d.i)b&&g.ak(d,b+"."+d.i),g.bk(d,d.B);else{var e=window.location;d=kRa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Tu&&g.Fb(a.Tu,function(f,h){g.gk(d,h,f)});
g.gk(d,"VER",a.hp);E7(a,d);return d},kSa=function(){},lSa=function(){this.i=[];
this.u=[]},mSa=function(a,b){this.action=a;
this.params=b||{}},K7=function(a,b){g.I.call(this);
this.i=new g.M(this.vV,0,this);g.J(this,this.i);this.Rf=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.D)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.D)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},L7=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.xa=a;this.J=b;this.B=new g.mr;this.u=new K7(this.oW,this);this.i=null;this.ea=!1;this.D=null;this.V="";this.N=this.C=0;this.K=[];this.Aa=c;this.ma=d;this.Ba=e},nSa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.GA,sessionId:a.i.B,arrayId:a.i.ls}},oSa=function(a,b){a.N=b||0;
a.u.stop();M7(a);a.i&&(3==a.i.getState()&&gSa(a.i),bSa(a.i));a.N=0},N7=function(a){return!!a.i&&3==a.i.getState()},M7=function(a){if(a.i){var b=a.ma(),c=a.i.Xj||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.Xj=c}},O7=function(a){this.port=this.domain="";
this.i="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.pi(4,a))||"";b&&(this.port=":"+b);this.domain=g.qi(a)||"";a=g.ad;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Jc(a,"10.0")&&(this.u=!1))},P7=function(a,b){var c=a.i;
a.u&&(c="https://"+a.domain+a.port+a.i);return g.Bi(c+b,{})},Q7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Oa(a.C,d,!0),onError:g.Oa(a.B,e),onTimeout:g.Oa(a.D,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.wt(b,a)},sSa=function(){var a=pSa;
qSa();R7.push(a);rSa()},S7=function(a,b){qSa();
var c=tSa(a,String(b));g.jb(R7)?uSa(c):(rSa(),g.Db(R7,function(d){d(c)}))},qSa=function(){R7||(R7=g.Ga("yt.mdx.remote.debug.handlers_")||[],g.Fa("yt.mdx.remote.debug.handlers_",R7,void 0))},uSa=function(a){var b=(T7+1)%50;
T7=b;U7[b]=a;V7||(V7=49==b)},rSa=function(){var a=R7;
if(U7[0]){var b=V7?T7:-1;do{b=(b+1)%50;var c=U7[b];g.Db(a,function(d){d(c)})}while(b!=T7);
U7=Array(50);T7=-1;V7=!1}},tSa=function(a,b){var c=(Date.now()-vSa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},W7=function(a){g.R.call(this);
this.J=a;this.screens=[]},wSa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c)return a=c.name,c.id=b.id||c.id,c.name=b.name,c.token=b.token,c.uuid=b.uuid||c.uuid,c.name!=a;a.screens.push(b);return!0},xSa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.No(a.screens,function(f){return!!Y6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=wSa(a,b[d])||c;return c},ySa=function(a,b){var c=a.screens.length;
a.screens=g.No(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},X7=function(a,b,c,d,e){g.R.call(this);
this.B=a;this.K=b;this.C=c;this.J=d;this.D=e;this.u=0;this.i=null;this.Lb=NaN},Z7=function(a){W7.call(this,"LocalScreenService");
this.u=a;this.i=NaN;Y7(this);this.info("Initializing with "+W6(this.screens))},zSa=function(a){if(a.screens.length){var b=g.Bm(a.screens,function(d){return d.id}),c=P7(a.u,"/pairing/get_lounge_token_batch");
Q7(a.u,c,{screen_ids:b.join(",")},(0,g.D)(a.lR,a),(0,g.D)(a.kR,a))}},Y7=function(a){if(g.us("deprecate_pair_servlet_enabled"))return xSa(a,[]);
var b=qRa(wRa());b=g.No(b,function(c){return!c.uuid});
return xSa(a,b)},$7=function(a,b){yRa(g.Bm(a.screens,oRa));
b&&xRa()},b8=function(a,b){g.R.call(this);
this.J=b;b=(b=g.Uz("yt-remote-online-screen-ids")||"")?b.split(","):[];for(var c={},d=this.J(),e=0,f=d.length;e<f;++e){var h=d[e].id;c[h]=g.ib(b,h)}this.i=c;this.D=a;this.B=this.C=NaN;this.u=null;a8("Initialized with "+g.Wh(this.i))},c8=function(a,b,c){var d=P7(a.D,"/pairing/get_screen_availability");
Q7(a.D,d,{lounge_token:b.token},(0,g.D)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.D)(function(){c(!1)},a))},d8=function(a,b){a:if(P6(b)!=P6(a.i))var c=!1;
else{c=g.Nb(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(a8("Updated online screens: "+g.Wh(a.i)),a.i=b,a.Z("screenChange"));ASa(a)},e8=function(a){isNaN(a.B)||g.qt(a.B);
a.B=g.ot((0,g.D)(a.WE,a),0<a.C&&a.C<g.Pa()?2E4:1E4)},a8=function(a){S7("OnlineScreenService",a)},BSa=function(a){var b={};
g.Db(a.J(),function(c){c.token?b[c.token]=c.id:this.Zd("Requesting availability of screen w/o lounge token.")});
return b},ASa=function(a){a=g.Nb(g.Gb(a.i,function(b){return b}));
g.Ab(a);a.length?g.Tz("yt-remote-online-screen-ids",a.join(","),60):g.Wz("yt-remote-online-screen-ids")},f8=function(a,b){b=void 0===b?!1:b;
W7.call(this,"ScreenService");this.C=a;this.K=b;this.i=this.u=null;this.B=[];this.D={};CSa(this)},ESa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var h=a.Gh(),l=c?Z6(h,c):null;c&&(a.K||l)||(l=Z6(h,b));if(l){l.uuid=b;var m=g8(a,l);c8(a.i,m,function(n){e(n?m:null)})}else c?DSa(a,c,(0,g.D)(function(n){var p=g8(this,new T6({name:d,
screenId:c,loungeToken:n,dialId:b||""}));c8(this.i,p,function(q){e(q?p:null)})},a),f):e(null)},FSa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},GSa=function(a,b,c){c8(a.i,b,c)},DSa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){f=h&&h.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.wt(P7(a.C,"/pairing/get_lounge_token_batch"),e)},HSa=function(a){a.screens=a.u.Gh();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+W6(a.screens))},CSa=function(a){h8(a);
a.u=new Z7(a.C);a.u.subscribe("screenChange",(0,g.D)(a.uR,a));HSa(a);a.K||(a.B=qRa(g.Uz("yt-remote-automatic-screen-cache")||[]));h8(a);a.info("Initializing automatic screens: "+W6(a.B));a.i=new b8(a.C,(0,g.D)(a.Gh,a,!0));a.i.subscribe("screenChange",(0,g.D)(function(){this.Z("onlineScreenChange")},a))},g8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=Z6(a.B,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.B.push(b),a.K||ISa(a));h8(a);a.D[b.uuid]=b.id;g.Tz("yt-remote-device-id-map",a.D,31536E3);return b},ISa=function(a){a=g.No(a.B,function(b){return"shortLived"!=b.idType});
g.Tz("yt-remote-automatic-screen-cache",g.Bm(a,oRa))},h8=function(a){a.D=g.Uz("yt-remote-device-id-map")||{}},i8=function(a,b,c){g.R.call(this);
this.Ba=c;this.B=a;this.i=b;this.C=null},j8=function(a,b){a.C=b;
a.Z("sessionScreen",a.C)},JSa=function(a,b){a.C&&(a.C.token=b,g8(a.B,a.C));
a.Z("sessionScreen",a.C)},k8=function(a,b){S7(a.Ba,b)},l8=function(a,b,c){i8.call(this,a,b,"CastSession");
var d=this;this.config_=c;this.u=null;this.ma=(0,g.D)(this.zP,this);this.Aa=(0,g.D)(this.PV,this);this.ea=g.ot(function(){KSa(d,null)},12E4);
this.K=this.D=this.J=this.N=0;this.xa=!1;this.V="unknown"},m8=function(a,b){g.qt(a.K);
a.K=0;0==b?LSa(a):a.K=g.ot(function(){LSa(a)},b)},LSa=function(a){MSa(a,"getLoungeToken");
g.qt(a.D);a.D=g.ot(function(){NSa(a,null)},3E4)},MSa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Wh(void 0));
var c={};c.type=b;a.u?a.u.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ha,(0,g.D)(function(){k8(this,"Failed to send message: "+b+".")},a)):k8(a,"Sending yt message without session: "+g.Wh(c))},n8=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.xJ(b,function(c){j8(a,c)},function(){return a.yg()},5)):a.yg(Error("Waiting for session status timed out."))},PSa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new T6(b);OSa(a,d,function(e){e?(a.xa=!0,g8(a.B,d),j8(a,d),a.V="unknown",m8(a,c)):(g.ys(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.yg())},5)},KSa=function(a,b){g.qt(a.ea);
a.ea=0;b?a.config_.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?PSa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.ys(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),n8(a,b.screenId))):(g.ys(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+
".")),n8(a,b.screenId)):n8(a,b.screenId):a.yg(Error("Waiting for session status timed out."))},NSa=function(a,b){g.qt(a.D);
a.D=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.V=c,m8(a,3E4)):(JSa(a,b.loungeToken),a.xa=!1,a.V="unknown",m8(a,b.loungeTokenRefreshIntervalMs))},OSa=function(a,b,c,d){g.qt(a.J);
a.J=0;GSa(a.B,b,function(e){e||0>d?c(e):a.J=g.ot(function(){OSa(a,b,c,d-1)},300)})},QSa=function(a){g.qt(a.N);
a.N=0;g.qt(a.J);a.J=0;g.qt(a.ea);a.ea=0;g.qt(a.D);a.D=0;g.qt(a.K);a.K=0},o8=function(a,b,c,d){i8.call(this,a,b,"DialSession");
this.config_=d;this.u=this.N=null;this.Aa="";this.La=c;this.Ma=null;this.ea=g.Ha;this.V=NaN;this.Ha=(0,g.D)(this.AP,this);this.D=g.Ha;this.K=this.J=0;this.ma=!1;this.xa="unknown"},p8=function(a){var b;
return!!(a.config_.enableDialLoungeToken&&(null==(b=a.u)?0:b.getDialAppInfo))},RSa=function(a){a.D=a.B.bH(a.Aa,a.i.label,a.i.friendlyName,p8(a),function(b,c){a.D=g.Ha;
a.ma=!0;j8(a,b);"shortLived"==b.idType&&0<c&&q8(a,c)},function(b){a.D=g.Ha;
a.yg(b)})},SSa=function(a){var b={};
b.pairingCode=a.Aa;b.theme=a.La;BRa()&&(b.env_useStageMdx=1);return g.zi(b)},r8=function(a){return new Promise(function(b){a.Aa=X6();
if(a.Ma){var c=new chrome.cast.DialLaunchResponse(!0,SSa(a));b(c);RSa(a)}else a.ea=function(){g.qt(a.V);a.ea=function(){};
a.V=NaN;var d=new chrome.cast.DialLaunchResponse(!0,SSa(a));b(d);RSa(a)},a.V=g.ot(function(){a.ea()},100)})},USa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new T6(b);return(new Promise(function(e){TSa(a,d,function(f){f?(a.ma=!0,g8(a.B,d),j8(a,d),q8(a,c)):g.ys(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):r8(a)})},VSa=function(a,b){var c=a.N.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){ESa(a.B,c,b,d,function(f){f&&f.token&&j8(a,f);e(f)},function(f){k8(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):r8(a)})},TSa=function(a,b,c,d){g.qt(a.J);
a.J=0;GSa(a.B,b,function(e){e||0>d?c(e):a.J=g.ot(function(){TSa(a,b,c,d-1)},300)})},q8=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
p8(a)&&(g.qt(a.K),a.K=0,0==b?WSa(a):a.K=g.ot(function(){WSa(a)},b))},WSa=function(a){p8(a)&&a.u.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.xa=c,q8(a,3E4)):(a.ma=!1,a.xa="unknown",JSa(a,b.loungeToken),q8(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.xa="noLoungeTokenResponse";q8(a,3E4)})},XSa=function(a){g.qt(a.J);
a.J=0;g.qt(a.K);a.K=0;a.D();a.D=function(){};
g.qt(a.V)},s8=function(a,b){i8.call(this,a,b,"ManualSession");
this.u=g.ot((0,g.D)(this.qs,this,null),150)},t8=function(a,b){g.R.call(this);
this.config_=b;this.u=a;this.N=b.appId||"233637DE";this.C=b.theme||"cl";this.V=b.disableCastApi||!1;this.J=b.forceMirroring||!1;this.i=null;this.K=!1;this.B=[];this.D=(0,g.D)(this.JU,this)},YSa=function(a,b){return b?g.eb(a.B,function(c){return U6(b,c.label)},a):null},u8=function(a){S7("Controller",a)},pSa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},v8=function(a){return a.K||!!a.B.length||!!a.i},w8=function(a,b,c){b!=a.i&&(g.uf(a.i),(a.i=b)?(c?a.Z("yt-remote-cast2-receiver-resumed",
b.i):a.Z("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.D)(a.KL,a,b)),b.subscribe("sessionFailed",function(){return ZSa(a,b)}),b.getScreen()?a.Z("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.qs(null)):a.Z("yt-remote-cast2-session-change",null))},ZSa=function(a,b){a.i==b&&a.Z("yt-remote-cast2-session-failed")},$Sa=function(a){var b=a.u.aH(),c=a.i&&a.i.i;
a=g.Bm(b,function(d){c&&U6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=YSa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},eTa=function(a,b,c,d){d.disableCastApi?x8("Cannot initialize because disabled by Mdx config."):aTa()?bTa(b,d)&&(y8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?cTa(a,c):(window.__onGCastApiAvailable=function(e,f){e?cTa(a,c):(z8("Failed to load cast API: "+f),A8(!1),y8(!1),g.Wz("yt-remote-cast-available"),g.Wz("yt-remote-cast-receiver"),
dTa(),c(!1))},d.loadCastApiSetupScript?g.Yz("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=f7()&&IRa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?h7():89<=f7()?KRa():(i7(),g7(JRa.map(FRa))))):x8("Cannot initialize because not running Chrome")},dTa=function(){x8("dispose");
var a=B8();a&&a.dispose();g.Fa("yt.mdx.remote.cloudview.instance_",null,void 0);fTa(!1);g.dv(C8);C8.length=0},D8=function(){return!!g.Uz("yt-remote-cast-installed")},gTa=function(){var a=g.Uz("yt-remote-cast-receiver");
return a?a.friendlyName:null},hTa=function(){x8("clearCurrentReceiver");
g.Wz("yt-remote-cast-receiver")},iTa=function(){return D8()?B8()?B8().getCastSession():(z8("getCastSelector: Cast is not initialized."),null):(z8("getCastSelector: Cast API is not installed!"),null)},F8=function(){D8()?B8()?E8()?(x8("Requesting cast selector."),B8().requestSession()):(x8("Wait for cast API to be ready to request the session."),C8.push(g.cv("yt-remote-cast2-api-ready",F8))):z8("requestCastSelector: Cast is not initialized."):z8("requestCastSelector: Cast API is not installed!")},G8=
function(a,b){E8()?B8().setConnectedScreenStatus(a,b):z8("setConnectedScreenStatus called before ready.")},aTa=function(){var a=0<=g.ad.search(/ (CrMo|Chrome|CriOS)\//);
return g.lj||a},jTa=function(a,b){B8().init(a,b)},bTa=function(a,b){var c=!1;
B8()||(a=new t8(a,b),a.subscribe("yt-remote-cast2-availability-change",function(d){g.Tz("yt-remote-cast-available",d);R6("yt-remote-cast2-availability-change",d)}),a.subscribe("yt-remote-cast2-receiver-selected",function(d){x8("onReceiverSelected: "+d.friendlyName);
g.Tz("yt-remote-cast-receiver",d);R6("yt-remote-cast2-receiver-selected",d)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(d){x8("onReceiverResumed: "+d.friendlyName);
g.Tz("yt-remote-cast-receiver",d);R6("yt-remote-cast2-receiver-resumed",d)}),a.subscribe("yt-remote-cast2-session-change",function(d){x8("onSessionChange: "+V6(d));
d||g.Wz("yt-remote-cast-receiver");R6("yt-remote-cast2-session-change",d)}),g.Fa("yt.mdx.remote.cloudview.instance_",a,void 0),c=!0);
x8("cloudview.createSingleton_: "+c);return c},B8=function(){return g.Ga("yt.mdx.remote.cloudview.instance_")},cTa=function(a,b){A8(!0);
y8(!1);jTa(a,function(c){c?(fTa(!0),g.ev("yt-remote-cast2-api-ready")):(z8("Failed to initialize cast API."),A8(!1),g.Wz("yt-remote-cast-available"),g.Wz("yt-remote-cast-receiver"),dTa());b(c)})},x8=function(a){S7("cloudview",a)},z8=function(a){S7("cloudview",a)},A8=function(a){x8("setCastInstalled_ "+a);
g.Tz("yt-remote-cast-installed",a)},E8=function(){return!!g.Ga("yt.mdx.remote.cloudview.apiReady_")},fTa=function(a){x8("setApiReady_ "+a);
g.Fa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},y8=function(a){g.Fa("yt.mdx.remote.cloudview.initializing_",a,void 0)},H8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.J=this.K=0;this.trackData=null;this.hasNext=this.Ck=!1;this.N=this.D=this.i=this.C=0;this.B=NaN;this.u=!1;this.reset(a)},I8=function(a){a.audioTrackId=null;
a.trackData=null;a.playerState=-1;a.Ck=!1;a.hasNext=!1;a.K=0;a.J=g.Pa();a.C=0;a.i=0;a.D=0;a.N=0;a.B=NaN;a.u=!1},J8=function(a){return a.xc()?(g.Pa()-a.J)/1E3:0},K8=function(a,b){a.K=b;
a.J=g.Pa()},L8=function(a){switch(a.playerState){case 1:case 1081:return(g.Pa()-a.J)/1E3+a.K;
case -1E3:return 0}return a.K},M8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&I8(a)},N8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.trackData);b.hasPrevious=a.Ck;b.hasNext=a.hasNext;b.playerTime=a.K;b.playerTimeAt=a.J;b.seekableStart=a.C;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.N;b.liveIngestionTime=a.B;return b},P8=function(a,b){g.R.call(this);
this.B=0;this.C=a;this.J=[];this.D=new lSa;this.u=this.i=null;this.V=(0,g.D)(this.iT,this);this.K=(0,g.D)(this.cw,this);this.N=(0,g.D)(this.hT,this);this.ea=(0,g.D)(this.pT,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.kF,this),kTa(this))):c=3;0!=c&&(b?this.kF(c):g.ot((0,g.D)(function(){this.kF(c)},this),0));
(a=iTa())&&O8(this,a);this.subscribe("yt-remote-cast2-session-change",this.ea)},Q8=function(a){return new H8(a.C.getPlayerContextData())},kTa=function(a){g.Db("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange multiStateLoopEnabled".split(" "),function(b){this.J.push(this.C.subscribe(b,g.Oa(this.GU,b),this))},a)},lTa=function(a){g.Db(a.J,function(b){this.C.unsubscribeByKey(b)},a);
a.J.length=0},R8=function(a){return 1==a.getState()},S8=function(a,b){var c=a.D;
50>c.i.length+c.u.length&&a.D.u.push(b)},U8=function(a,b,c){var d=Q8(a);
K8(d,c);-1E3!=d.playerState&&(d.playerState=b);T8(a,d)},V8=function(a,b,c){a.C.sendMessage(b,c)},T8=function(a,b){lTa(a);
a.C.setPlayerContextData(N8(b));kTa(a)},O8=function(a,b){a.u&&(a.u.removeUpdateListener(a.V),a.u.removeMediaListener(a.K),a.cw(null));
a.u=b;a.u&&(S7("CP","Setting cast session: "+a.u.sessionId),a.u.addUpdateListener(a.V),a.u.addMediaListener(a.K),a.u.media.length&&a.cw(a.u.media[0]))},mTa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=Q8(a);b.contentId!=d.videoId&&S7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;K8(d,a.i.getEstimatedTime());T8(a,d)}else S7("CP","No cast media video. Ignoring state update.")},W8=function(a,b,c){return(0,g.D)(function(d){this.Zd("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Zd("Retrying "+b+" using MDx browser channel."),V8(this,b,c))},a)},X8=function(a,b,c,d){d=void 0===d?!1:d;
g.R.call(this);this.D=NaN;this.xa=!1;this.N=this.K=this.ea=this.ma=NaN;this.V=[];this.C=this.J=this.B=this.jc=this.i=null;this.Ha=a;this.Ba=d;this.V.push(g.vu(window,"beforeunload",(0,g.D)(this.gR,this)));this.u=[];this.jc=new H8;this.Ma=b.id;this.Aa=b.idType;this.i=nTa(this,c);this.i.subscribe("handlerOpened",this.mT,this);this.i.subscribe("handlerClosed",this.jT,this);this.i.subscribe("handlerError",this.kT,this);this.i.subscribe("handlerMessage",this.lT,this);this.i.kA(b.token);this.subscribe("remoteQueueChange",
function(){var e=this.jc.videoId;g.Xz()&&g.Tz("yt-remote-session-video-id",e)},this)},oTa=function(a){return g.eb(a.u,function(b){return"LOUNGE_SCREEN"==b.type})},Y8=function(a){S7("conn",a)},nTa=function(a,b){return new L7(P7(a.Ha,"/bc"),b,!1,function(){return a.fH()},"shortLived"==a.Aa)},Z8=function(a,b){a.Z("proxyStateChange",b)},pTa=function(a){a.D=g.ot((0,g.D)(function(){Y8("Connecting timeout");
this.Fr(1)},a),2E4)},$8=function(a){g.qt(a.D);
a.D=NaN},a9=function(a){g.qt(a.ma);
a.ma=NaN},qTa=function(a){b9(a);
a.ea=g.ot((0,g.D)(function(){c9(this,"getNowPlaying")},a),2E4)},b9=function(a){g.qt(a.ea);
a.ea=NaN},sTa=function(a,b){var c=null;
if(b){var d=oTa(a);d&&(c={clientName:d.clientName,deviceMake:d.brand,deviceModel:d.model,osVersion:d.osVersion})}g.Fa("yt.mdx.remote.remoteClient_",c,void 0);b&&($8(a),a9(a));c=N7(a.i)&&isNaN(a.D);b==c?b&&(Z8(a,1),c9(a,"getSubtitlesTrack")):b?(a.wJ()&&a.jc.reset(),Z8(a,1),c9(a,"getNowPlaying"),rTa(a)):a.Fr(1)},tTa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.jc.videoId&&(g.Wb(b.params)?a.jc.trackData=null:a.jc.trackData=b.params,a.Z("remotePlayerChange"))},uTa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.jc.listId=b.params.listId||a.jc.listId;M8(a.jc,c,d);a.Z("remoteQueueChange")},wTa=function(a,b){b.params=b.params||{};
uTa(a,b);vTa(a,b);a.Z("autoplayDismissed")},vTa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
K8(a.jc,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.jc.playerState&&(c=-1E3);a.jc.playerState=c;c=Number(b.params.loadedTime);a.jc.N=isNaN(c)?0:c;a.jc.Gj(Number(b.params.duration));c=a.jc;var d=Number(b.params.liveIngestionTime);c.B=d;c.u=isNaN(d)?!1:!0;c=a.jc;d=Number(b.params.seekableStartTime);b=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.i=isNaN(b)?0:b;1==a.jc.playerState?qTa(a):b9(a);a.Z("remotePlayerChange")},xTa=function(a,b){if(-1E3!=a.jc.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.jc.playerState=c;b=parseInt(b.params.currentTime,10);K8(a.jc,isNaN(b)?0:b);a.Z("remotePlayerChange")}},yTa=function(a,b){var c="true"==b.params.muted;
a.jc.volume=parseInt(b.params.volume,10);a.jc.muted=c;a.Z("remotePlayerChange")},zTa=function(a,b){a.J=b.params.videoId;
a.Z("nowAutoplaying",parseInt(b.params.timeout,10))},ATa=function(a,b){var c="true"==b.params.hasNext;
a.jc.Ck="true"==b.params.hasPrevious;a.jc.hasNext=c;a.Z("previousNextChange")},rTa=function(a){g.qt(a.N);
a.N=g.ot((0,g.D)(a.Fr,a,1),864E5)},c9=function(a,b,c){c?Y8("Sending: action="+b+", params="+g.Wh(c)):Y8("Sending: action="+b);
a.i.sendMessage(b,c)},d9=function(a){W7.call(this,"ScreenServiceProxy");
this.Me=a;this.i=[];this.i.push(this.Me.$_s("screenChange",(0,g.D)(this.EP,this)));this.i.push(this.Me.$_s("onlineScreenChange",(0,g.D)(this.nU,this)))},ETa=function(a,b){ARa();
if(!e7||!e7.get("yt-remote-disable-remote-module-for-dev")){b=g.P("MDX_CONFIG")||b;sRa();c7();e9||(e9=new O7(b?b.loungeApiHost:void 0),BRa()&&(e9.i="/api/loungedev"));f9||(f9=g.Ga("yt.mdx.remote.deferredProxies_")||[],g.Fa("yt.mdx.remote.deferredProxies_",f9,void 0));BTa();var c=g9();if(!c){var d=new f8(e9,b?b.disableAutomaticScreenCache||!1:!1);g.Fa("yt.mdx.remote.screenService_",d,void 0);c=g9();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,
disableCastApi:b.disableCastApi,enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken,forceMirroring:b.forceMirroring});g.Fa("yt.mdx.remote.enableConnectWithInitialState_",b?b.enableConnectWithInitialState||!1:!1,void 0);eTa(a,d,function(f){f?h9()&&G8(h9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){R6("yt-remote-receiver-availability-change")})},e)}b&&!g.Ga("yt.mdx.remote.initialized_")&&(g.Fa("yt.mdx.remote.initialized_",!0,void 0),i9("Initializing: "+
g.Wh(b)),j9.push(g.cv("yt-remote-cast2-api-ready",function(){R6("yt-remote-api-ready")})),j9.push(g.cv("yt-remote-cast2-availability-change",function(){R6("yt-remote-receiver-availability-change")})),j9.push(g.cv("yt-remote-cast2-receiver-selected",function(){k9(null);
R6("yt-remote-auto-connect","cast-selector-receiver")})),j9.push(g.cv("yt-remote-cast2-receiver-resumed",function(){R6("yt-remote-receiver-resumed","cast-selector-receiver")})),j9.push(g.cv("yt-remote-cast2-session-change",CTa)),j9.push(g.cv("yt-remote-connection-change",function(f){f?G8(h9(),"YouTube TV"):l9()||(G8(null,null),hTa())})),j9.push(g.cv("yt-remote-cast2-session-failed",function(){R6("yt-remote-connection-failed")})),a=m9(),b.isAuto&&(a.id+="#dial"),e=b.capabilities||[],g.us("desktop_enable_autoplay")&&
e.push("atp"),0<e.length&&(a.capabilities=e),a.name=b.device,a.app=b.app,(b=b.theme)&&(a.theme=b),i9(" -- with channel params: "+g.Wh(a)),a?(g.Tz("yt-remote-session-app",a.app),g.Tz("yt-remote-session-name",a.name)):(g.Wz("yt-remote-session-app"),g.Wz("yt-remote-session-name")),g.Fa("yt.mdx.remote.channelParams_",a,void 0),c.start(),h9()||DTa())}},FTa=function(){var a=g9().Me.$_gos();
var b=n9();b&&o9()&&(Y6(a,b)||a.push(b));return rRa(a)},p9=function(){var a=GTa();
!a&&D8()&&gTa()&&(a={key:"cast-selector-receiver",name:gTa()});return a},GTa=function(){var a=FTa(),b=n9();
b||(b=l9());return g.eb(a,function(c){return b&&U6(b,c.key)?!0:!1})},n9=function(){var a=h9();
if(!a)return null;var b=g9().Gh();return Z6(b,a)},CTa=function(a){i9("remote.onCastSessionChange_: "+V6(a));
if(a){var b=n9();if(b&&b.id==a.id){if(G8(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))q9&&(q9.token=a),(b=o9())&&b.kA(a)}else b&&r9(),s9(a,1)}else o9()&&r9()},r9=function(){E8()?B8().stopSession():z8("stopSession called before API ready.");
var a=o9();a&&(a.disconnect(1),t9(null))},u9=function(){var a=o9();
return!!a&&3!=a.getProxyState()},i9=function(a){S7("remote",a)},g9=function(){if(!v9){var a=g.Ga("yt.mdx.remote.screenService_");
v9=a?new d9(a):null}return v9},h9=function(){return g.Ga("yt.mdx.remote.currentScreenId_")},HTa=function(a){g.Fa("yt.mdx.remote.currentScreenId_",a,void 0)},ITa=function(){return g.Ga("yt.mdx.remote.connectData_")},k9=function(a){g.Fa("yt.mdx.remote.connectData_",a,void 0)},o9=function(){return g.Ga("yt.mdx.remote.connection_")},t9=function(a){var b=o9();
k9(null);a||HTa("");g.Fa("yt.mdx.remote.connection_",a,void 0);f9&&(g.Db(f9,function(c){c(a)}),f9.length=0);
b&&!a?R6("yt-remote-connection-change",!1):!b&&a&&R6("yt-remote-connection-change",!0)},l9=function(){var a=g.Xz();
if(!a)return null;var b=g9();if(!b)return null;b=b.Gh();return Z6(b,a)},s9=function(a,b){h9();
n9()&&n9();if(w9)q9=a;else{HTa(a.id);var c=g.Ga("yt.mdx.remote.enableConnectWithInitialState_")||!1;a=new X8(e9,a,m9(),c);a.connect(b,ITa());a.subscribe("beforeDisconnect",function(d){R6("yt-remote-before-disconnect",d)});
a.subscribe("beforeDispose",function(){o9()&&(o9(),t9(null))});
a.subscribe("browserChannelAuthError",function(){var d=n9();d&&"shortLived"==d.idType&&(E8()?B8().handleBrowserChannelAuthError():z8("refreshLoungeToken called before API ready."))});
t9(a)}},DTa=function(){var a=l9();
a?(i9("Resume connection to: "+V6(a)),s9(a,0)):(d7(),hTa(),i9("Skipping connecting because no session screen found."))},BTa=function(){var a=m9();
if(g.Wb(a)){a=b7();var b=g.Uz("yt-remote-session-name")||"",c=g.Uz("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Fa("yt.mdx.remote.channelParams_",a,void 0)}},m9=function(){return g.Ga("yt.mdx.remote.channelParams_")||{}},x9=function(a,b,c){g.I.call(this);
var d=this;this.u=a;this.I=b;this.Rb=c;this.events=new g.FD(this);this.ea=this.events.S(this.I,"onVolumeChange",function(e){JTa(d,e)});
this.D=!1;this.J=new g.bK(64);this.i=new g.M(this.MM,500,this);this.B=new g.M(this.OM,1E3,this);this.N=new j7(this.cX,0,this);this.C={};this.V=new g.M(this.vN,1E3,this);this.K=new k7(this.seekTo,1E3,this);this.ma=g.Ha;g.J(this,this.events);this.events.S(b,"onCaptionsTrackListChanged",this.VT);this.events.S(b,"captionschanged",this.fT);this.events.S(b,"captionssettingschanged",this.UM);this.events.S(b,"videoplayerreset",this.Hz);this.events.S(b,"mdxautoplaycancel",function(){d.Rb.SI()});
a=this.Rb;a.isDisposed();a.subscribe("proxyStateChange",this.GL,this);a.subscribe("remotePlayerChange",this.jw,this);a.subscribe("remoteQueueChange",this.Hz,this);a.subscribe("previousNextChange",this.DL,this);a.subscribe("nowAutoplaying",this.xL,this);a.subscribe("autoplayDismissed",this.aL,this);g.J(this,this.i);g.J(this,this.B);g.J(this,this.N);g.J(this,this.V);g.J(this,this.K);this.UM();this.Hz();this.jw()},JTa=function(a,b){if(y9(a)){a.Rb.unsubscribe("remotePlayerChange",a.jw,a);
var c=Math.round(b.volume);b=!!b.muted;var d=Q8(a.Rb);if(c!==d.volume||b!==d.muted)a.Rb.setVolume(c,b),a.V.start();a.Rb.subscribe("remotePlayerChange",a.jw,a)}},KTa=function(a){a.Ob(0);
a.i.stop();a.Sb(new g.bK(64))},z9=function(a,b){if(y9(a)&&!a.D){var c=null;
b&&(c={style:a.I.getSubtitlesUserSettings()},g.ec(c,b));a.Rb.eH(a.I.getVideoData(1).videoId,c);a.C=Q8(a.Rb).trackData}},A9=function(a,b){var c=a.I.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.I.getVideoData(1);a.Rb.playVideo(c.videoId,b,d,e,c.playerParams,c.Xa,hRa(c));a.Sb(new g.bK(1))},LTa=function(a,b){if(b){var c=a.I.getOption("captions","tracklist",{SJ:1});
c&&c.length?(a.I.setOption("captions","track",b),a.D=!1):(a.I.loadModule("captions"),a.D=!0)}else a.I.setOption("captions","track",{})},y9=function(a){return Q8(a.Rb).videoId===a.I.getVideoData(1).videoId},B9=function(){g.W.call(this,{G:"div",
L:"ytp-mdx-manual-pairing-popup-dialog",X:{role:"dialog"},T:[{G:"div",L:"ytp-mdx-manual-pairing-popup-dialog-inner-content",T:[{G:"div",L:"ytp-mdx-manual-pairing-popup-title",va:"Connecting to your TV on web using a code will be going away soon"},{G:"div",L:"ytp-mdx-manual-pairing-popup-buttons",T:[{G:"button",Ia:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],va:"Learn more"},{G:"button",Ia:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],va:"OK"}]}]}]});this.i=new g.HL(this,250);this.learnMoreButton=
this.Fa("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.Fa("ytp-mdx-manual-pairing-popup-ok");g.J(this,this.i);this.S(this.learnMoreButton,"click",this.u);this.S(this.okButton,"click",this.B)},C9=function(){g.W.call(this,{G:"div",
L:"ytp-mdx-popup-dialog",X:{role:"dialog"},T:[{G:"div",L:"ytp-mdx-popup-dialog-inner-content",T:[{G:"div",L:"ytp-mdx-popup-title",va:"You're signed out"},{G:"div",L:"ytp-mdx-popup-description",va:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{G:"div",L:"ytp-mdx-privacy-popup-buttons",T:[{G:"button",Ia:["ytp-button","ytp-mdx-privacy-popup-cancel"],va:"Cancel"},{G:"button",Ia:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],va:"Confirm"}]}]}]});this.i=new g.HL(this,250);this.cancelButton=this.Fa("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.Fa("ytp-mdx-privacy-popup-confirm");g.J(this,this.i);this.S(this.cancelButton,"click",this.u);this.S(this.confirmButton,"click",this.B)},D9=function(a){g.W.call(this,{G:"div",
L:"ytp-remote",T:[{G:"div",L:"ytp-remote-display-status",T:[{G:"div",L:"ytp-remote-display-status-icon",T:[g.ysa()]},{G:"div",L:"ytp-remote-display-status-text",va:"{{statustext}}"}]}]});this.api=a;this.i=new g.HL(this,250);g.J(this,this.i);this.S(a,"presentingplayerstatechange",this.u);MTa(this,a.wb())},MTa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
b=g.U(b,128)?g.zI("Error on $RECEIVER_NAME",c):b.xc()||g.U(b,4)?g.zI("Playing on $RECEIVER_NAME",c):g.zI("Connected to $RECEIVER_NAME",c);a.Ua("statustext",b);a.i.show()}else a.i.hide()},E9=function(a,b){g.UP.call(this,"Play on",0,a,b);
this.I=a;this.ao={};this.S(a,"onMdxReceiversChange",this.D);this.S(a,"presentingplayerstatechange",this.D);this.D()},F9=function(a){g.fN.call(this,a);
this.sj={key:X6(),name:"This computer"};this.ci=null;this.subscriptions=[];this.LE=this.Rb=null;this.ao=[this.sj];this.Vm=this.sj;this.pd=new g.bK(64);this.sK=0;this.mf=-1;this.xs=null;this.pw=this.gz=!1;this.lm=this.Is=null;if(!g.nF(this.player.W())&&!g.oF(this.player.W())){a=this.player;var b=g.KM(a);b&&(b=b.An())&&(b=new E9(a,b),g.J(this,b));b=new D9(a);g.J(this,b);g.UM(a,b.element,4);this.Is=new C9;g.J(this,this.Is);g.UM(a,this.Is.element,4);this.player.W().experiments.Ga("pair_servlet_deprecation_warning_enabled")&&
!this.player.W().experiments.Ga("deprecate_pair_servlet_enabled")&&(this.xs=new B9,g.J(this,this.xs),g.UM(a,this.xs.element,4));this.pw=!!l9();this.gz=!!g.Uz("yt-remote-manual-pairing-warning-shown")}},G9=function(a){a.lm&&(a.player.removeEventListener("presentingplayerstatechange",a.lm),a.lm=null)},NTa=function(a,b,c){a.pd=c;
a.player.Z("presentingplayerstatechange",new g.lI(c,b))},OTa=function(a,b,c){var d=!1;
1===b?d=!a.pw:2===b&&(d=!a.gz);d&&g.nI(c,8)&&(a.player.pauseVideo(),G9(a))},H9=function(a,b){if(b.key!==a.Vm.key)if(b.key===a.sj.key)r9();
else{if(a.xs&&!a.gz&&b!==a.sj&&"cast-selector-receiver"!==b.key&&g.EF(a.player.W()))PTa(a);else{var c;(c=!a.player.W().experiments.Ga("mdx_enable_privacy_disclosure_ui"))||(c=((c=g.P("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.P("SESSION_INDEX")&&!g.P("LOGGED_IN")))||a.pw||!a.Is);(c?0:g.EF(a.player.W())||g.HF(a.player.W()))&&QTa(a)}a.Vm=b;if(!a.player.W().U("disable_mdx_connection_in_mdx_module_for_music_web")||!g.oF(a.player.W())){var d=a.player.getPlaylistId();c=a.player.getVideoData(1);
var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&a.player.W().experiments.Ga("should_clear_video_data_on_player_cued_unstarted"))a=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=g.$M(f,l).videoId}else h=[e];f=a.player.getCurrentTime(1);a={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Xa,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=hRa(c))&&(a.locationInfo=c)}i9("Connecting to: "+
g.Wh(b));"cast-selector-receiver"==b.key?(k9(a||null),b=a||null,E8()?B8().setLaunchParams(b):z8("setLaunchParams called before ready.")):!a&&u9()&&h9()==b.key?R6("yt-remote-connection-change",!0):(r9(),k9(a||null),a=g9().Gh(),(b=Z6(a,b.key))&&s9(b,1))}}},QTa=function(a){a.player.wb().xc()?a.player.pauseVideo():(a.lm=function(b){OTa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.lm));
a.Is&&a.Is.bd();o9()||(w9=!0)},PTa=function(a){a.player.wb().xc()?a.player.pauseVideo():(a.lm=function(b){OTa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.lm));
a.xs&&a.xs.bd();o9()||(w9=!0)},QRa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},w7={"'":"\\'"},nRa={cY:"atp",G8:"ska",u7:"que",r5:"mus",F8:"sus",E1:"dsp",P7:"seq",U4:"mic",z0:"dpa",qY:"cds",p5:"mlm"},e7,a7="",HRa=CRa("loadCastFramework")||CRa("loadCastApplicationFramework"),JRa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Qa(j7,g.I);g.k=j7.prototype;g.k.sP=function(a){this.C=arguments;this.i=!1;this.Lb?this.B=g.Pa()+this.Rf:this.Lb=g.vh(this.D,this.Rf)};
g.k.stop=function(){this.Lb&&(g.C.clearTimeout(this.Lb),this.Lb=null);this.B=null;this.i=!1;this.C=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.i&&(this.i=!1,this.J.apply(null,this.C)))};
g.k.ya=function(){this.stop();j7.Yd.ya.call(this)};
g.k.tP=function(){this.Lb&&(g.C.clearTimeout(this.Lb),this.Lb=null);this.B?(this.Lb=g.vh(this.D,this.B-g.Pa()),this.B=null):this.u?this.i=!0:(this.i=!1,this.J.apply(null,this.C))};g.w(k7,g.I);g.k=k7.prototype;g.k.ZG=function(a){this.B=arguments;this.Lb||this.u?this.i=!0:l7(this)};
g.k.stop=function(){this.Lb&&(g.C.clearTimeout(this.Lb),this.Lb=null,this.i=!1,this.B=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.i||this.Lb||(this.i=!1,l7(this))};
g.k.ya=function(){g.I.prototype.ya.call(this);this.stop()};m7.prototype.stringify=function(a){return g.C.JSON.stringify(a,void 0)};
m7.prototype.parse=function(a){return g.C.JSON.parse(a,void 0)};var o7=new g.Wf;g.w(LRa,g.xf);g.k=q7.prototype;g.k.Oo=null;g.k.Am=!1;g.k.wt=null;g.k.ZF=null;g.k.Ns=null;g.k.Zs=null;g.k.Pm=null;g.k.po=null;g.k.jq=null;g.k.Jf=null;g.k.LA=0;g.k.Lj=null;g.k.IA=null;g.k.Jm=null;g.k.St=-1;g.k.CM=!0;g.k.gp=!1;g.k.AB=0;g.k.Yz=null;var ORa={},t7={};g.k=q7.prototype;g.k.setTimeout=function(a){this.u=a};
g.k.uP=function(a){a=a.target;var b=this.Yz;b&&3==g.Wi(a)?b.ZG():this.DN(a)};
g.k.DN=function(a){try{if(a==this.Jf)a:{var b=g.Wi(this.Jf),c=this.Jf.u,d=this.Jf.getStatus();if(g.ke&&!g.ce(10)||g.xg&&!g.be("420+")){if(4>b)break a}else if(3>b||3==b&&!g.aj(this.Jf))break a;this.gp||4!=b||7==c||(8==c||0>=d?this.i.vj(3):this.i.vj(2));x7(this);var e=this.Jf.getStatus();this.St=e;var f=g.aj(this.Jf);if(this.Am=200==e){4==b&&u7(this);if(this.D){for(a=!0;!this.gp&&this.LA<f.length;){var h=PRa(this,f);if(h==t7){4==b&&(this.Jm=4,p7(15),a=!1);break}else if(h==ORa){this.Jm=4;p7(16);a=!1;
break}else y7(this,h)}4==b&&0==f.length&&(this.Jm=1,p7(17),a=!1);this.Am=this.Am&&a;a||(u7(this),v7(this))}else y7(this,f);this.Am&&!this.gp&&(4==b?this.i.tx(this):(this.Am=!1,s7(this)))}else 400==e&&0<f.indexOf("Unknown SID")?(this.Jm=3,p7(13)):(this.Jm=0,p7(14)),u7(this),v7(this)}}catch(l){this.Jf&&g.aj(this.Jf)}finally{}};
g.k.EV=function(a){n7((0,g.D)(this.CV,this,a),0)};
g.k.CV=function(a){this.gp||(x7(this),y7(this,a),s7(this))};
g.k.OL=function(a){n7((0,g.D)(this.BV,this,a),0)};
g.k.BV=function(a){this.gp||(u7(this),this.Am=a,this.i.tx(this),this.i.vj(4))};
g.k.cancel=function(){this.gp=!0;u7(this)};
g.k.LV=function(){this.wt=null;var a=Date.now();0<=a-this.ZF?(2!=this.Zs&&this.i.vj(3),u7(this),this.Jm=2,p7(18),v7(this)):SRa(this,this.ZF-a)};
g.k.getLastError=function(){return this.Jm};g.k=VRa.prototype;g.k.BB=null;g.k.nh=null;g.k.Zz=!1;g.k.PM=null;g.k.by=null;g.k.ND=null;g.k.CB=null;g.k.Xh=null;g.k.bl=-1;g.k.Tt=null;g.k.xu=null;g.k.connect=function(a){this.CB=a;a=A7(this.i,null,this.CB);p7(3);this.PM=Date.now();var b=this.i.N;null!=b?(this.Tt=b[0],(this.xu=b[1])?(this.Xh=1,WRa(this)):(this.Xh=2,C7(this))):(O6(a,"MODE","init"),this.nh=new q7(this,void 0,void 0,void 0),this.nh.Oo=this.BB,r7(this.nh,a,!1,null,!0),this.Xh=0)};
g.k.pQ=function(a){if(a)this.Xh=2,C7(this);else{p7(4);var b=this.i;b.Yj=b.Tm.bl;J7(b,9)}a&&this.vj(2)};
g.k.AC=function(a){return this.i.AC(a)};
g.k.abort=function(){this.nh&&(this.nh.cancel(),this.nh=null);this.bl=-1};
g.k.jf=function(){return!1};
g.k.HL=function(a,b){this.bl=a.St;if(0==this.Xh)if(b){try{var c=this.u.parse(b)}catch(d){a=this.i;a.Yj=this.bl;J7(a,2);return}this.Tt=c[0];this.xu=c[1]}else a=this.i,a.Yj=this.bl,J7(a,2);else if(2==this.Xh)if(this.Zz)p7(7),this.ND=Date.now();else if("11111"==b){if(p7(6),this.Zz=!0,this.by=Date.now(),a=this.by-this.PM,!g.ke||g.ce(10)||500>a)this.bl=200,this.nh.cancel(),p7(12),B7(this.i,this,!0)}else p7(8),this.by=this.ND=Date.now(),this.Zz=!1};
g.k.tx=function(){this.bl=this.nh.St;if(this.nh.Am)0==this.Xh?this.xu?(this.Xh=1,WRa(this)):(this.Xh=2,C7(this)):2==this.Xh&&((!g.ke||g.ce(10)?!this.Zz:200>this.ND-this.by)?(p7(11),B7(this.i,this,!1)):(p7(12),B7(this.i,this,!0)));else{0==this.Xh?p7(9):2==this.Xh&&p7(10);var a=this.i;this.nh.getLastError();a.Yj=this.bl;J7(a,2)}};
g.k.Nw=function(){return this.i.Nw()};
g.k.isActive=function(){return this.i.isActive()};
g.k.vj=function(a){this.i.vj(a)};g.k=D7.prototype;g.k.Xj=null;g.k.Tu=null;g.k.Vg=null;g.k.De=null;g.k.DB=null;g.k.dy=null;g.k.fI=null;g.k.vx=null;g.k.Vv=0;g.k.vS=0;g.k.Kf=null;g.k.hn=null;g.k.zl=null;g.k.qp=null;g.k.Tm=null;g.k.GA=null;g.k.ls=-1;g.k.rK=-1;g.k.Yj=-1;g.k.Jr=0;g.k.rr=0;g.k.hp=8;g.Qa(YRa,g.xf);g.Qa(ZRa,g.xf);g.k=D7.prototype;g.k.connect=function(a,b,c,d,e){p7(0);this.DB=b;this.Tu=c||{};d&&void 0!==e&&(this.Tu.OSID=d,this.Tu.OAID=e);this.J?(n7((0,g.D)(this.BI,this,a),100),cSa(this)):this.BI(a)};
g.k.BI=function(a){this.Tm=new VRa(this);this.Tm.BB=this.Xj;this.Tm.u=this.D;this.Tm.connect(a)};
g.k.jf=function(){return 0==this.i};
g.k.getState=function(){return this.i};
g.k.ML=function(a){this.hn=null;gSa(this,a)};
g.k.LL=function(){this.zl=null;this.De=new q7(this,this.B,"rpc",this.K);this.De.Oo=this.Xj;this.De.AB=0;var a=this.fI.clone();g.gk(a,"RID","rpc");g.gk(a,"SID",this.B);g.gk(a,"CI",this.GA?"0":"1");g.gk(a,"AID",this.ls);E7(this,a);if(!g.ke||g.ce(10))g.gk(a,"TYPE","xmlhttp"),r7(this.De,a,!0,this.vx,!1);else{g.gk(a,"TYPE","html");var b=this.De,c=!!this.vx;b.Zs=3;b.Pm=N6(a.clone());RRa(b,c)}};
g.k.HL=function(a,b){if(0!=this.i&&(this.De==a||this.Vg==a))if(this.Yj=a.St,this.Vg==a&&3==this.i)if(7<this.hp){try{var c=this.D.parse(b)}catch(d){c=null}if(Array.isArray(c)&&3==c.length)if(a=c,0==a[0])a:{if(!this.zl){if(this.De)if(this.De.Ns+3E3<this.Vg.Ns)G7(this),this.De.cancel(),this.De=null;else break a;I7(this);p7(19)}}else this.rK=a[1],0<this.rK-this.ls&&37500>a[2]&&this.GA&&0==this.rr&&!this.qp&&(this.qp=n7((0,g.D)(this.cT,this),6E3));else J7(this,11)}else null!=b&&J7(this,11);else if(this.De==
a&&G7(this),!g.xc(b))for(a=this.D.parse(b),b=0;b<a.length;b++)c=a[b],this.ls=c[0],c=c[1],2==this.i?"c"==c[0]?(this.B=c[1],this.vx=c[2],c=c[3],null!=c?this.hp=c:this.hp=6,this.i=3,this.Kf&&this.Kf.xI(),this.fI=A7(this,this.Nw()?this.vx:null,this.DB),hSa(this)):"stop"==c[0]&&J7(this,7):3==this.i&&("stop"==c[0]?J7(this,7):"noop"!=c[0]&&this.Kf&&this.Kf.wI(c),this.rr=0)};
g.k.cT=function(){null!=this.qp&&(this.qp=null,this.De.cancel(),this.De=null,I7(this),p7(20))};
g.k.tx=function(a){if(this.De==a){G7(this);this.De=null;var b=2}else if(this.Vg==a)this.Vg=null,b=1;else return;this.Yj=a.St;if(0!=this.i)if(a.Am)if(1==b){b=Date.now()-a.Ns;var c=o7;c.dispatchEvent(new YRa(c,a.jq?a.jq.length:0,b,this.Jr));F7(this);this.C.length=0}else hSa(this);else{c=a.getLastError();var d;if(!(d=3==c||7==c||0==c&&0<this.Yj)){if(d=1==b)this.Vg||this.hn||1==this.i||2<=this.Jr?d=!1:(this.hn=n7((0,g.D)(this.ML,this,a),iSa(this,this.Jr)),this.Jr++,d=!0);d=!(d||2==b&&I7(this))}if(d)switch(c){case 1:J7(this,
5);break;case 4:J7(this,10);break;case 3:J7(this,6);break;case 7:J7(this,12);break;default:J7(this,2)}}};
g.k.PQ=function(a){if(!g.ib(arguments,this.i))throw Error("Unexpected channel state: "+this.i);};
g.k.MW=function(a){a?p7(2):(p7(1),jSa(this,8))};
g.k.AC=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Ii;a.N=!1;return a};
g.k.isActive=function(){return!!this.Kf&&this.Kf.isActive(this)};
g.k.vj=function(a){var b=o7;b.dispatchEvent(new ZRa(b,a))};
g.k.Nw=function(){return!(!g.ke||g.ce(10))};
g.k=kSa.prototype;g.k.xI=function(){};
g.k.wI=function(){};
g.k.vI=function(){};
g.k.nC=function(){};
g.k.jJ=function(){return{}};
g.k.isActive=function(){return!0};g.k=lSa.prototype;g.k.isEmpty=function(){return 0===this.i.length&&0===this.u.length};
g.k.clear=function(){this.i=[];this.u=[]};
g.k.contains=function(a){return g.ib(this.i,a)||g.ib(this.u,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.sLa)(b,a);0<=c?(g.nb(b,c),b=!0):b=!1;return b||g.ob(this.u,a)};
g.k.Yg=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Qa(K7,g.I);g.k=K7.prototype;g.k.vV=function(){this.Rf=Math.min(3E5,2*this.Rf);this.B();this.u&&this.start()};
g.k.start=function(){var a=this.Rf+15E3*Math.random();g.Nq(this.i,a);this.u=Date.now()+a};
g.k.stop=function(){this.i.stop();this.u=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Rf=5E3};g.Qa(L7,kSa);g.k=L7.prototype;g.k.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.k.ag=function(a){return this.B.ag(a)};
g.k.Z=function(a,b){return this.B.Z.apply(this.B,arguments)};
g.k.dispose=function(){this.ea||(this.ea=!0,g.uf(this.B),oSa(this),g.uf(this.u),this.u=null,this.ma=function(){return""})};
g.k.isDisposed=function(){return this.ea};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.V="";this.u.stop();this.D=a||null;this.C=b||0;a=this.xa+"/test";b=this.xa+"/bind";var d=new D7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.Aa),e=this.i;e&&(e.Kf=null);d.Kf=this;this.i=d;M7(this);if(this.i){d=g.P("ID_TOKEN");var f=this.i.Xj||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.Xj=f}e?(3!=e.getState()&&0==eSa(e)||e.getState(),this.i.connect(a,b,this.J,e.B,e.ls)):c?this.i.connect(a,
b,this.J,c.sessionId,c.arrayId):this.i.connect(a,b,this.J)}};
g.k.sendMessage=function(a,b){a={_sc:a};b&&g.ec(a,b);this.u.isActive()||2==(this.i?this.i.getState():0)?this.K.push(a):N7(this)&&(M7(this),dSa(this.i,a))};
g.k.xI=function(){this.u.reset();this.D=null;this.C=0;if(this.K.length){var a=this.K;this.K=[];for(var b=0,c=a.length;b<c;++b)dSa(this.i,a[b])}this.Z("handlerOpened")};
g.k.vI=function(a){var b=2==a&&401==this.i.Yj;4==a||b||this.u.start();this.Z("handlerError",a,b)};
g.k.nC=function(a){if(!this.u.isActive())this.Z("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.K.push(d)}};
g.k.jJ=function(){var a={v:2};this.V&&(a.gsessionid=this.V);0!=this.C&&(a.ui=""+this.C);0!=this.N&&(a.ui=""+this.N);this.D&&g.ec(a,this.D);return a};
g.k.wI=function(a){"S"==a[0]?this.V=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),bSa(this.i)):this.Z("handlerMessage",new mSa(a[0],a[1]))};
g.k.kA=function(a){(this.J.loungeIdToken=a)||this.u.stop();if(this.Ba&&this.i){var b=this.i.Xj||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.Xj=b}};
g.k.oW=function(){this.u.isActive();0==eSa(this.i)&&this.connect(this.D,this.C)};O7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
O7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
O7.prototype.D=function(a){a(Error("request timed out"))};var vSa=Date.now(),R7=null,U7=Array(50),T7=-1,V7=!1;g.Qa(W7,g.R);W7.prototype.Gh=function(){return this.screens};
W7.prototype.contains=function(a){return!!Y6(this.screens,a)};
W7.prototype.get=function(a){return a?Z6(this.screens,a):null};
W7.prototype.info=function(a){S7(this.J,a)};g.w(X7,g.R);g.k=X7.prototype;g.k.start=function(){!this.i&&isNaN(this.Lb)&&this.WL()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.Lb)||(g.qt(this.Lb),this.Lb=NaN)};
g.k.ya=function(){this.stop();g.R.prototype.ya.call(this)};
g.k.WL=function(){this.Lb=NaN;this.i=g.wt(P7(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.K},timeout:5E3,onSuccess:(0,g.D)(this.wP,this),onError:(0,g.D)(this.vP,this),onTimeout:(0,g.D)(this.xP,this)})};
g.k.wP=function(a,b){this.i=null;a=b.screen||{};a.dialId=this.C;a.name=this.J;b=-1;this.D&&a.shortLivedLoungeToken&&a.shortLivedLoungeToken.value&&a.shortLivedLoungeToken.refreshIntervalMs&&(a.screenIdType="shortLived",a.loungeToken=a.shortLivedLoungeToken.value,b=a.shortLivedLoungeToken.refreshIntervalMs);this.Z("pairingComplete",new T6(a),b)};
g.k.vP=function(a){this.i=null;a.status&&404==a.status?this.u>=RTa.length?this.Z("pairingFailed",Error("DIAL polling timed out")):(a=RTa[this.u],this.Lb=g.ot((0,g.D)(this.WL,this),a),this.u++):this.Z("pairingFailed",Error("Server error "+a.status))};
g.k.xP=function(){this.i=null;this.Z("pairingFailed",Error("Server not responding"))};
var RTa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Qa(Z7,W7);g.k=Z7.prototype;g.k.start=function(){Y7(this)&&this.Z("screenChange");!g.Uz("yt-remote-lounge-token-expiration")&&zSa(this);g.qt(this.i);this.i=g.ot((0,g.D)(this.start,this),1E4)};
g.k.add=function(a,b){Y7(this);wSa(this,a);$7(this,!1);this.Z("screenChange");b(a);a.token||zSa(this)};
g.k.remove=function(a,b){var c=Y7(this);ySa(this,a)&&($7(this,!1),c=!0);b(a);c&&this.Z("screenChange")};
g.k.EA=function(a,b,c,d){var e=Y7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,$7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.Z("screenChange")};
g.k.ya=function(){g.qt(this.i);Z7.Yd.ya.call(this)};
g.k.lR=function(a){Y7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}$7(this,!b);b&&S7(this.J,"Missed "+b+" lounge tokens.")};
g.k.kR=function(a){S7(this.J,"Requesting lounge tokens failed: "+a)};g.w(b8,g.R);g.k=b8.prototype;g.k.start=function(){var a=parseInt(g.Uz("yt-remote-fast-check-period")||"0",10);(this.C=g.Pa()-144E5<a?0:a)?e8(this):(this.C=g.Pa()+3E5,g.Tz("yt-remote-fast-check-period",this.C),this.WE())};
g.k.isEmpty=function(){return g.Wb(this.i)};
g.k.update=function(){a8("Updating availability on schedule.");var a=this.J(),b=g.Gb(this.i,function(c,d){return c&&!!Z6(a,d)},this);
d8(this,b)};
g.k.ya=function(){g.qt(this.B);this.B=NaN;this.u&&(this.u.abort(),this.u=null);g.R.prototype.ya.call(this)};
g.k.WE=function(){g.qt(this.B);this.B=NaN;this.u&&this.u.abort();var a=BSa(this);if(P6(a)){var b=P7(this.D,"/pairing/get_screen_availability");this.u=Q7(this.D,b,{lounge_token:g.Nb(a).join(",")},(0,g.D)(this.cV,this,a),(0,g.D)(this.bV,this))}else d8(this,{}),e8(this)};
g.k.cV=function(a,b){this.u=null;var c=g.Nb(BSa(this));if(g.Bb(c,g.Nb(a))){b=b.screens||[];c={};for(var d=0,e=b.length;d<e;++d)c[a[b[d].loungeToken]]="online"==b[d].status;d8(this,c);e8(this)}else this.Zd("Changing Screen set during request."),this.WE()};
g.k.bV=function(a){this.Zd("Screen availability failed: "+a);this.u=null;e8(this)};
g.k.Zd=function(a){S7("OnlineScreenService",a)};g.Qa(f8,W7);g.k=f8.prototype;g.k.start=function(){this.u.start();this.i.start();this.screens.length&&(this.Z("screenChange"),this.i.isEmpty()||this.Z("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.i.update()};
g.k.EA=function(a,b,c,d){this.u.contains(a)?this.u.EA(a,b,c,d):(a="Updating name of unknown screen: "+a.name,S7(this.J,a),d(Error(a)))};
g.k.Gh=function(a){return a?this.screens:g.rb(this.screens,g.No(this.B,function(b){return!this.contains(b)},this))};
g.k.aH=function(){return g.No(this.Gh(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.bH=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new X7(this.C,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.uf(l);e(g8(h,m),n)});
l.subscribe("pairingFailed",function(m){g.uf(l);f(m)});
l.start();return(0,g.D)(l.stop,l)};
g.k.yP=function(a,b,c,d){g.wt(P7(this.C,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.D)(function(e,f){e=new T6(f.screen||{});if(!e.name||FSa(this,e.name)){a:{f=e.name;for(var h=2,l=b(f,h);FSa(this,l);){h++;if(20<h)break a;l=b(f,h)}f=l}e.name=f}c(g8(this,e))},this),
onError:(0,g.D)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.D)(function(){d(Error("pairing request timed out."))},this)})};
g.k.ya=function(){g.uf(this.u);g.uf(this.i);f8.Yd.ya.call(this)};
g.k.uR=function(){HSa(this);this.Z("screenChange");this.i.update()};
f8.prototype.dispose=f8.prototype.dispose;g.Qa(i8,g.R);g.k=i8.prototype;g.k.getScreen=function(){return this.C};
g.k.yg=function(a){this.isDisposed()||(a&&(k8(this,""+a),this.Z("sessionFailed")),this.C=null,this.Z("sessionScreen",null))};
g.k.info=function(a){S7(this.Ba,a)};
g.k.cH=function(){return null};
g.k.jF=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.D)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.D)(function(){k8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.ya=function(){this.jF("");i8.Yd.ya.call(this)};g.w(l8,i8);g.k=l8.prototype;g.k.iF=function(a){if(this.u){if(this.u==a)return;k8(this,"Overriding cast session with new session object");QSa(this);this.xa=!1;this.V="unknown";this.u.removeUpdateListener(this.ma);this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa)}this.u=a;this.u.addUpdateListener(this.ma);this.u.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa);MSa(this,"getMdxSessionStatus")};
g.k.qs=function(a){this.info("launchWithParams no-op for Cast: "+g.Wh(a))};
g.k.stop=function(){this.u?this.u.stop((0,g.D)(function(){this.yg()},this),(0,g.D)(function(){this.yg(Error("Failed to stop receiver app."))},this)):this.yg(Error("Stopping cast device without session."))};
g.k.jF=function(){};
g.k.ya=function(){this.info("disposeInternal");QSa(this);this.u&&(this.u.removeUpdateListener(this.ma),this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa));this.u=null;i8.prototype.ya.call(this)};
g.k.PV=function(a,b){if(!this.isDisposed())if(b)if(b=Q6(b),g.La(b))switch(a=""+b.type,b=b.data||{},this.info("onYoutubeMessage_: "+a+" "+g.Wh(b)),a){case "mdxSessionStatus":KSa(this,b);break;case "loungeToken":NSa(this,b);break;default:k8(this,"Unknown youtube message: "+a)}else k8(this,"Unable to parse message.");else k8(this,"No data in message.")};
g.k.xJ=function(a,b,c,d){g.qt(this.N);this.N=0;ESa(this.B,this.i.label,a,this.i.friendlyName,(0,g.D)(function(e){e?b(e):0<=d?(k8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.N=g.ot((0,g.D)(this.xJ,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.cH=function(){return this.u};
g.k.zP=function(a){this.isDisposed()||a||(k8(this,"Cast session died."),this.yg())};g.w(o8,i8);g.k=o8.prototype;g.k.iF=function(a){this.u=a;this.u.addUpdateListener(this.Ha)};
g.k.qs=function(a){this.Ma=a;this.ea()};
g.k.stop=function(){XSa(this);this.u?this.u.stop((0,g.D)(this.yg,this,null),(0,g.D)(this.yg,this,"Failed to stop DIAL device.")):this.yg()};
g.k.ya=function(){XSa(this);this.u&&this.u.removeUpdateListener(this.Ha);this.u=null;i8.prototype.ya.call(this)};
g.k.AP=function(a){this.isDisposed()||a||(k8(this,"DIAL session died."),this.D(),this.D=g.Ha,this.yg())};g.w(s8,i8);s8.prototype.stop=function(){this.yg()};
s8.prototype.iF=function(){};
s8.prototype.qs=function(){g.qt(this.u);this.u=NaN;var a=Z6(this.B.Gh(),this.i.label);a?j8(this,a):this.yg(Error("No such screen"))};
s8.prototype.ya=function(){g.qt(this.u);this.u=NaN;i8.prototype.ya.call(this)};g.w(t8,g.R);g.k=t8.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.N);this.V||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED;a=a||this.J?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;var e=(0,g.D)(this.MU,this);c=new chrome.cast.ApiConfig(c,(0,g.D)(this.IL,this),e,d,a);c.customDialLaunchCallback=(0,g.D)(this.xT,this);chrome.cast.initialize(c,(0,g.D)(function(){this.isDisposed()||
(chrome.cast.addReceiverActionListener(this.D),sSa(),this.u.subscribe("onlineScreenChange",(0,g.D)(this.dH,this)),this.B=$Sa(this),chrome.cast.setCustomReceivers(this.B,g.Ha,(0,g.D)(function(f){this.Zd("Failed to set initial custom receivers: "+g.Wh(f))},this)),this.Z("yt-remote-cast2-availability-change",v8(this)),b(!0))},this),(0,g.D)(function(f){this.Zd("Failed to initialize API: "+g.Wh(f));
b(!1)},this))};
g.k.tW=function(a,b){u8("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)u8("Unsetting old screen status: "+this.i.i.friendlyName),w8(this,null)}if(a&&b){if(!this.i){c=Z6(this.u.Gh(),a);if(!c){u8("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){u8("setConnectedScreenStatus: Screen with id type to be short lived.");return}a=YSa(this,c);a||(u8("setConnectedScreenStatus: Connected receiver not custom..."),a=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),a.receiverType=chrome.cast.ReceiverType.CUSTOM,this.B.push(a),chrome.cast.setCustomReceivers(this.B,g.Ha,(0,g.D)(function(d){this.Zd("Failed to set initial custom receivers: "+g.Wh(d))},this)));
u8("setConnectedScreenStatus: new active receiver: "+a.friendlyName);w8(this,new s8(this.u,a),!0)}this.i.jF(b)}else u8("setConnectedScreenStatus: no screen.")};
g.k.uW=function(a){this.isDisposed()?this.Zd("Setting connection data on disposed cast v2"):this.i?this.i.qs(a):this.Zd("Setting connection data without a session")};
g.k.CP=function(){this.isDisposed()?this.Zd("Stopping session on disposed cast v2"):this.i?(this.i.stop(),w8(this,null)):u8("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.D)(this.IL,this),(0,g.D)(this.fV,this))};
g.k.ya=function(){this.u.unsubscribe("onlineScreenChange",(0,g.D)(this.dH,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.D);var a=pSa,b=g.Ga("yt.mdx.remote.debug.handlers_");g.ob(b||[],a);g.uf(this.i);g.R.prototype.ya.call(this)};
g.k.Zd=function(a){S7("Controller",a)};
g.k.KL=function(a,b){this.i==a&&(b||w8(this,null),this.Z("yt-remote-cast2-session-change",b))};
g.k.JU=function(a,b){if(!this.isDisposed())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),u8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)u8("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{u8("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.Z("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:w8(this,
new s8(this.u,a));break;case chrome.cast.ReceiverType.DIAL:w8(this,new o8(this.u,a,this.C,this.config_));break;case chrome.cast.ReceiverType.CAST:w8(this,new l8(this.u,a,this.config_));break;default:this.Zd("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.Zd("Stopping receiver w/o session: "+a.friendlyName)}else this.Zd("onReceiverAction_ called without receiver.")};
g.k.xT=function(a){if(this.isDisposed())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Zd("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.Zd("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return u8("Reselecting dial screen."),
this.Z("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Zd('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);w8(this,new o8(this.u,b,this.C,this.config_))}b=this.i;b.N=a;b.N.appState==chrome.cast.DialAppState.RUNNING?(a=b.N.extraData||{},c=a.screenId||null,p8(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=USa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.N.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.ys(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=VSa(b,c)):a=VSa(b,c)):a=r8(b);return a};
g.k.IL=function(a){var b=this;if(!this.isDisposed()&&!this.J){u8("New cast session ID: "+a.sessionId);var c=a.receiver;if(c.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(c.receiverType==chrome.cast.ReceiverType.CAST)u8("Got resumed cast session before resumed mdx connection."),c.friendlyName=chrome.cast.unescape(c.friendlyName),w8(this,new l8(this.u,c,this.config_),!0);else{this.Zd("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var d=this.i.i,e=Z6(this.u.Gh(),
d.label);e&&U6(e,c.label)&&d.receiverType!=chrome.cast.ReceiverType.CAST&&c.receiverType==chrome.cast.ReceiverType.CAST&&(u8("onSessionEstablished_: manual to cast session change "+c.friendlyName),g.uf(this.i),this.i=new l8(this.u,c,this.config_),this.i.subscribe("sessionScreen",(0,g.D)(this.KL,this,this.i)),this.i.subscribe("sessionFailed",function(){return ZSa(b,b.i)}),this.i.qs(null));
this.i.iF(a)}}};
g.k.BP=function(){return this.i?this.i.cH():null};
g.k.fV=function(a){this.isDisposed()||(this.Zd("Failed to estabilish a session: "+g.Wh(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&w8(this,null),this.Z("yt-remote-cast2-session-failed"))};
g.k.MU=function(a){u8("Receiver availability updated: "+a);if(!this.isDisposed()){var b=v8(this);this.K=a==chrome.cast.ReceiverAvailability.AVAILABLE;v8(this)!=b&&this.Z("yt-remote-cast2-availability-change",v8(this))}};
g.k.dH=function(){this.isDisposed()||(this.B=$Sa(this),u8("Updating custom receivers: "+g.Wh(this.B)),chrome.cast.setCustomReceivers(this.B,g.Ha,(0,g.D)(function(){this.Zd("Failed to set custom receivers.")},this)),this.Z("yt-remote-cast2-availability-change",v8(this)))};
t8.prototype.setLaunchParams=t8.prototype.uW;t8.prototype.setConnectedScreenStatus=t8.prototype.tW;t8.prototype.stopSession=t8.prototype.CP;t8.prototype.getCastSession=t8.prototype.BP;t8.prototype.requestSession=t8.prototype.requestSession;t8.prototype.init=t8.prototype.init;t8.prototype.dispose=t8.prototype.dispose;var C8=[];g.k=H8.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";I8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.trackData=a.trackData,this.Ck=a.hasPrevious,this.hasNext=a.hasNext,this.K=a.playerTime,this.J=a.playerTimeAt,this.C=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.N=a.loadedTime,this.B=a.liveIngestionTime,this.u=
!isNaN(this.B))};
g.k.xc=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.Gj=function(a){this.D=isNaN(a)?0:a};
g.k.getDuration=function(){return this.u?this.D+J8(this):this.D};
g.k.clone=function(){return new H8(N8(this))};g.w(P8,g.R);g.k=P8.prototype;g.k.getState=function(){return this.B};
g.k.play=function(){R8(this)?(this.i?this.i.play(null,g.Ha,W8(this,"play")):V8(this,"play"),U8(this,1,L8(Q8(this))),this.Z("remotePlayerChange")):S8(this,this.play)};
g.k.pause=function(){R8(this)?(this.i?this.i.pause(null,g.Ha,W8(this,"pause")):V8(this,"pause"),U8(this,2,L8(Q8(this))),this.Z("remotePlayerChange")):S8(this,this.pause)};
g.k.seekTo=function(a){if(R8(this)){if(this.i){var b=Q8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.xc()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ha,W8(this,"seekTo",{newTime:a}))}else V8(this,"seekTo",{newTime:a});U8(this,3,a);this.Z("remotePlayerChange")}else S8(this,g.Oa(this.seekTo,a))};
g.k.stop=function(){if(R8(this)){this.i?this.i.stop(null,g.Ha,W8(this,"stopVideo")):V8(this,"stopVideo");var a=Q8(this);a.index=-1;a.videoId="";I8(a);T8(this,a);this.Z("remotePlayerChange")}else S8(this,this.stop)};
g.k.setVolume=function(a,b){if(R8(this)){var c=Q8(this);if(this.u){if(c.volume!=a){var d=Math.round(a)/100;this.u.setReceiverVolumeLevel(d,(0,g.D)(function(){S7("CP","set receiver volume: "+d)},this),(0,g.D)(function(){this.Zd("failed to set receiver volume.")},this))}c.muted!=b&&this.u.setReceiverMuted(b,(0,g.D)(function(){S7("CP","set receiver muted: "+b)},this),(0,g.D)(function(){this.Zd("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);V8(this,"setVolume",e)}c.muted=b;c.volume=a;T8(this,c)}else S8(this,g.Oa(this.setVolume,a,b))};
g.k.eH=function(a,b){if(R8(this)){var c=Q8(this);a={videoId:a};b&&(c.trackData={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},a.style=g.Wh(b.style),g.ec(a,c.trackData));V8(this,"setSubtitlesTrack",a);T8(this,c)}else S8(this,g.Oa(this.eH,a,b))};
g.k.setAudioTrack=function(a,b){R8(this)?(b=b.getLanguageInfo().getId(),V8(this,"setAudioTrack",{videoId:a,audioTrackId:b}),a=Q8(this),a.audioTrackId=b,T8(this,a)):S8(this,g.Oa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){d=void 0===d?null:d;e=void 0===e?null:e;f=void 0===f?null:f;h=void 0===h?null:h;var l=Q8(this),m={videoId:a};void 0!==c&&(m.currentIndex=c);M8(l,a,c||0);void 0!==b&&(K8(l,b),m.currentTime=b);d&&(m.listId=d);e&&(m.playerParams=e);f&&(m.clickTrackingParams=f);h&&(m.locationInfo=g.Wh(h));V8(this,"setPlaylist",m);d||T8(this,l)};
g.k.Sz=function(a,b){if(R8(this)){if(a&&b){var c=Q8(this);M8(c,a,b);T8(this,c)}V8(this,"previous")}else S8(this,g.Oa(this.Sz,a,b))};
g.k.nextVideo=function(a,b){if(R8(this)){if(a&&b){var c=Q8(this);M8(c,a,b);T8(this,c)}V8(this,"next")}else S8(this,g.Oa(this.nextVideo,a,b))};
g.k.SI=function(){R8(this)?V8(this,"dismissAutoplay"):S8(this,this.SI)};
g.k.dispose=function(){if(3!=this.B){var a=this.B;this.B=3;this.Z("proxyStateChange",a,this.B)}g.R.prototype.dispose.call(this)};
g.k.ya=function(){lTa(this);this.C=null;this.D.clear();O8(this,null);g.R.prototype.ya.call(this)};
g.k.kF=function(a){if((a!=this.B||2==a)&&3!=this.B&&0!=a){var b=this.B;this.B=a;this.Z("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)b=a=this.D,0===b.i.length&&(b.i=b.u,b.i.reverse(),b.u=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.GU=function(a,b){this.Z(a,b)};
g.k.iT=function(a){if(!a)this.cw(null),O8(this,null);else if(this.u.receiver.volume){a=this.u.receiver.volume;var b=Q8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)S7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,T8(this,b)}};
g.k.cw=function(a){S7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.N);if(this.i=a)this.i.addUpdateListener(this.N),mTa(this),this.Z("remotePlayerChange")};
g.k.hT=function(a){a?(mTa(this),this.Z("remotePlayerChange")):this.cw(null)};
g.k.DF=function(){V8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.pT=function(){var a=iTa();a&&O8(this,a)};
g.k.Zd=function(a){S7("CP",a)};g.w(X8,g.R);g.k=X8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.videoIds,f=b.playerParams,h=b.clickTrackingParams,l=b.index,m={videoId:d},n=b.currentTime,p=b.locationInfo;b=b.loopMode;void 0!==n&&(m.currentTime=5>=n?0:n);f&&(m.playerParams=f);p&&(m.locationInfo=p);h&&(m.clickTrackingParams=h);c&&(m.listId=c);e&&0<e.length&&(m.videoIds=e.join(","));void 0!==l&&(m.currentIndex=l);this.Ba&&(m.loopMode=b||"LOOP_MODE_OFF");c&&(this.jc.listId=c);this.jc.videoId=d;this.jc.index=l||0;this.jc.state=3;K8(this.jc,
n);this.C="UNSUPPORTED";c=this.Ba?"setInitialState":"setPlaylist";Y8("Connecting with "+c+" and params: "+g.Wh(m));this.i.connect({method:c,params:g.Wh(m)},a,vRa())}else Y8("Connecting without params"),this.i.connect({},a,vRa());pTa(this)};
g.k.kA=function(a){this.i.kA(a)};
g.k.dispose=function(){this.isDisposed()||(g.Fa("yt.mdx.remote.remoteClient_",null,void 0),this.Z("beforeDispose"),Z8(this,3));g.R.prototype.dispose.call(this)};
g.k.ya=function(){$8(this);b9(this);a9(this);g.qt(this.K);this.K=NaN;g.qt(this.N);this.N=NaN;this.B=null;g.wu(this.V);this.V.length=0;this.i.dispose();g.R.prototype.ya.call(this);this.C=this.J=this.u=this.jc=this.i=null};
g.k.gR=function(){this.Fr(2)};
g.k.mT=function(){Y8("Channel opened");this.xa&&(this.xa=!1,a9(this),this.ma=g.ot((0,g.D)(function(){Y8("Timing out waiting for a screen.");this.Fr(1)},this),15E3));
zRa(nSa(this.i),this.Ma)};
g.k.jT=function(){Y8("Channel closed");isNaN(this.D)?d7(!0):d7();this.dispose()};
g.k.kT=function(a,b){d7();isNaN(this.xv())?(b&&"shortLived"==this.Aa&&this.Z("browserChannelAuthError",a),Y8("Channel error: "+a+" without reconnection"),this.dispose()):(this.xa=!0,Y8("Channel error: "+a+" with reconnection in "+this.xv()+" ms"),Z8(this,2))};
g.k.dK=function(a){if(!this.u||0===this.u.length)return!1;for(var b=g.r(this.u),c=b.next();!c.done;c=b.next())if(!c.value.capabilities.has(a))return!1;return!0};
g.k.lT=function(a){a.params?Y8("Received: action="+a.action+", params="+g.Wh(a.params)):Y8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=Q6(a.params.devices);this.u=g.Bm(a,function(c){return new S6(c)});
a=!!g.eb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
sTa(this,a);a=this.dK("mlm");this.Z("multiStateLoopEnabled",a);break;case "loungeScreenDisconnected":g.qb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
sTa(this,!1);break;case "remoteConnected":var b=new S6(Q6(a.params.device));g.eb(this.u,function(c){return b?c.id==b.id:!1})||iRa(this.u,b);
break;case "remoteDisconnected":b=new S6(Q6(a.params.device));g.qb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":uTa(this,a);break;case "nowPlaying":wTa(this,a);break;case "onStateChange":vTa(this,a);break;case "onAdStateChange":xTa(this,a);break;case "onVolumeChanged":yTa(this,a);break;case "onSubtitlesTrackChanged":tTa(this,a);break;case "nowAutoplaying":zTa(this,a);break;case "autoplayDismissed":this.Z("autoplayDismissed");break;case "autoplayUpNext":this.J=a.params.videoId||null;this.Z("autoplayUpNext",this.J);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.Z("autoplayModeChange",this.C);"DISABLED"==this.C&&this.Z("autoplayDismissed");break;case "onHasPreviousNextChanged":ATa(this,a);break;case "requestAssistedSignIn":this.Z("assistedSignInRequested",a.params.authCode);break;case "onLoopModeChanged":this.Z("loopModeChange",a.params.loopMode);break;default:Y8("Unrecognized action: "+a.action)}};
g.k.iW=function(){if(this.B){var a=this.B;this.B=null;this.jc.videoId!=a&&c9(this,"getNowPlaying")}};
g.k.dR=function(){var a=3;this.isDisposed()||(a=0,isNaN(this.xv())?N7(this.i)&&isNaN(this.D)&&(a=1):a=2);return a};
g.k.Fr=function(a){Y8("Disconnecting with "+a);g.Fa("yt.mdx.remote.remoteClient_",null,void 0);$8(this);this.Z("beforeDisconnect",a);1==a&&d7();oSa(this.i,a);this.dispose()};
g.k.bR=function(){var a=this.jc;this.B&&(a=this.jc.clone(),M8(a,this.B,a.index));return N8(a)};
g.k.vW=function(a){var b=new H8(a);b.videoId&&b.videoId!=this.jc.videoId&&(this.B=b.videoId,g.qt(this.K),this.K=g.ot((0,g.D)(this.iW,this),5E3));var c=[];this.jc.listId==b.listId&&this.jc.videoId==b.videoId&&this.jc.index==b.index||c.push("remoteQueueChange");this.jc.playerState==b.playerState&&this.jc.volume==b.volume&&this.jc.muted==b.muted&&L8(this.jc)==L8(b)&&g.Wh(this.jc.trackData)==g.Wh(b.trackData)||c.push("remotePlayerChange");this.jc.reset(a);g.Db(c,function(d){this.Z(d)},this)};
g.k.wJ=function(){var a=this.i.J.id,b=g.eb(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.xv=function(){var a=this.i;return a.u.isActive()?a.u.u-Date.now():NaN};
g.k.YQ=function(){return this.C||"UNSUPPORTED"};
g.k.ZQ=function(){return this.J||""};
g.k.DP=function(){if(!isNaN(this.xv())){var a=this.i.u;g.Oq(a.i);a.start()}};
g.k.sW=function(a,b){c9(this,a,b);rTa(this)};
g.k.fH=function(){var a=g.Jt("SID","")||"",b=g.Jt("SAPISID","")||"",c=g.Jt("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.fe(g.Xa(a),2);b=g.fe(g.Xa(b),2);c=g.fe(g.Xa(c),2);return g.fe(g.Xa(a+","+b+","+c),2)};
X8.prototype.subscribe=X8.prototype.subscribe;X8.prototype.unsubscribeByKey=X8.prototype.ag;X8.prototype.getProxyState=X8.prototype.dR;X8.prototype.disconnect=X8.prototype.Fr;X8.prototype.getPlayerContextData=X8.prototype.bR;X8.prototype.setPlayerContextData=X8.prototype.vW;X8.prototype.getOtherConnectedRemoteId=X8.prototype.wJ;X8.prototype.getReconnectTimeout=X8.prototype.xv;X8.prototype.getAutoplayMode=X8.prototype.YQ;X8.prototype.getAutoplayVideoId=X8.prototype.ZQ;X8.prototype.reconnect=X8.prototype.DP;
X8.prototype.sendMessage=X8.prototype.sW;X8.prototype.getXsrfToken=X8.prototype.fH;X8.prototype.isCapabilitySupportedOnConnectedDevices=X8.prototype.dK;g.w(d9,W7);g.k=d9.prototype;g.k.Gh=function(a){return this.Me.$_gs(a)};
g.k.contains=function(a){return!!this.Me.$_c(a)};
g.k.get=function(a){return this.Me.$_g(a)};
g.k.start=function(){this.Me.$_st()};
g.k.add=function(a,b,c){this.Me.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Me.$_r(a,b,c)};
g.k.EA=function(a,b,c,d){this.Me.$_un(a,b,c,d)};
g.k.ya=function(){for(var a=0,b=this.i.length;a<b;++a)this.Me.$_ubk(this.i[a]);this.i.length=0;this.Me=null;W7.prototype.ya.call(this)};
g.k.EP=function(){this.Z("screenChange")};
g.k.nU=function(){this.Z("onlineScreenChange")};
f8.prototype.$_st=f8.prototype.start;f8.prototype.$_gspc=f8.prototype.yP;f8.prototype.$_gsppc=f8.prototype.bH;f8.prototype.$_c=f8.prototype.contains;f8.prototype.$_g=f8.prototype.get;f8.prototype.$_a=f8.prototype.add;f8.prototype.$_un=f8.prototype.EA;f8.prototype.$_r=f8.prototype.remove;f8.prototype.$_gs=f8.prototype.Gh;f8.prototype.$_gos=f8.prototype.aH;f8.prototype.$_s=f8.prototype.subscribe;f8.prototype.$_ubk=f8.prototype.ag;var q9=null,w9=!1,e9=null,f9=null,v9=null,j9=[];g.w(x9,g.I);g.k=x9.prototype;g.k.ya=function(){g.I.prototype.ya.call(this);this.i.stop();this.B.stop();this.N.stop();this.ma();var a=this.Rb;a.unsubscribe("proxyStateChange",this.GL,this);a.unsubscribe("remotePlayerChange",this.jw,this);a.unsubscribe("remoteQueueChange",this.Hz,this);a.unsubscribe("previousNextChange",this.DL,this);a.unsubscribe("nowAutoplaying",this.xL,this);a.unsubscribe("autoplayDismissed",this.aL,this);this.Rb=this.u=null};
g.k.lj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Rb.B)if(y9(this)){if(!Q8(this.Rb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":Q8(this.Rb).xc()?this.Rb.pause():this.Rb.play();break;case "control_play":this.Rb.play();break;case "control_pause":this.Rb.pause();break;case "control_seek":this.K.ZG(c[0],c[1]);break;case "control_subtitles_set_track":z9(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.I.getCurrentTime();A9(this,0===c?void 0:c);break;case "control_seek":A9(this,c[0]);break;case "control_subtitles_set_track":z9(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.fT=function(a){this.N.sP(a)};
g.k.cX=function(a){this.lj("control_subtitles_set_track",g.Wb(a)?null:a)};
g.k.UM=function(){var a=this.I.getOption("captions","track");g.Wb(a)||z9(this,a)};
g.k.Ob=function(a){this.u.Ob(a,this.I.getVideoData().lengthSeconds)};
g.k.VT=function(){g.Wb(this.C)||LTa(this,this.C);this.D=!1};
g.k.GL=function(a,b){this.B.stop();2===b&&this.OM()};
g.k.jw=function(){if(y9(this)){this.i.stop();var a=Q8(this.Rb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.mf=1;break;case 1082:case 1083:this.u.mf=0;break;default:this.u.mf=-1}switch(a.playerState){case 1081:case 1:this.Sb(new g.bK(8));this.MM();break;case 1085:case 3:this.Sb(new g.bK(9));break;case 1083:case 0:this.Sb(new g.bK(2));this.K.stop();this.Ob(this.I.getVideoData().lengthSeconds);break;case 1084:this.Sb(new g.bK(4));break;case 2:this.Sb(new g.bK(4));this.Ob(L8(a));
break;case -1:this.Sb(new g.bK(64));break;case -1E3:this.Sb(new g.bK(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=Q8(this.Rb).trackData;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,LTa(this,a));a=Q8(this.Rb);-1===a.volume||Math.round(this.I.getVolume())===a.volume&&this.I.isMuted()===a.muted||this.V.isActive()||this.vN()}else KTa(this)};
g.k.DL=function(){this.I.Z("mdxpreviousnextchange")};
g.k.Hz=function(){y9(this)||KTa(this)};
g.k.xL=function(a){isNaN(a)||this.I.Z("mdxnowautoplaying",a)};
g.k.aL=function(){this.I.Z("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){y9(this)&&this.Rb.setAudioTrack(this.I.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===Q8(this.Rb).playerState?A9(this,a):b&&this.Rb.seekTo(a)};
g.k.vN=function(){var a=this;if(y9(this)){var b=Q8(this.Rb);this.events.kc(this.ea);b.muted?this.I.mute():this.I.unMute();this.I.setVolume(b.volume);this.ea=this.events.S(this.I,"onVolumeChange",function(c){JTa(a,c)})}};
g.k.MM=function(){this.i.stop();if(!this.Rb.isDisposed()){var a=Q8(this.Rb);a.xc()&&this.Sb(new g.bK(8));this.Ob(L8(a));this.i.start()}};
g.k.OM=function(){this.B.stop();this.i.stop();var a=this.Rb.C.getReconnectTimeout();2==this.Rb.B&&!isNaN(a)&&this.B.start()};
g.k.Sb=function(a){this.B.stop();var b=this.J;if(!g.gK(b,a)){var c=g.U(a,2);c!==g.U(this.J,2)&&this.I.Rs(c);this.J=a;NTa(this.u,b,a)}};g.w(B9,g.W);B9.prototype.bd=function(){this.i.show()};
B9.prototype.Eb=function(){this.i.hide()};
B9.prototype.u=function(){g.JJ("https://support.google.com/youtube/answer/7640706")};
B9.prototype.B=function(){R6("mdx-manual-pairing-popup-ok");this.Eb()};g.w(C9,g.W);C9.prototype.bd=function(){this.i.show()};
C9.prototype.Eb=function(){this.i.hide()};
C9.prototype.u=function(){R6("mdx-privacy-popup-cancel");this.Eb()};
C9.prototype.B=function(){R6("mdx-privacy-popup-confirm");this.Eb()};g.w(D9,g.W);D9.prototype.u=function(a){MTa(this,a.state)};g.w(E9,g.UP);E9.prototype.D=function(){var a=this.I.getOption("remote","receivers");a&&1<a.length&&!this.I.getOption("remote","quickCast")?(this.ao=g.Eb(a,this.i,this),g.VP(this,g.Bm(a,this.i)),a=this.I.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.Wh(a),this.enable(!0)):this.enable(!1)};
E9.prototype.i=function(a){return a.key};
E9.prototype.bj=function(a){return"cast-selector-receiver"===a?"Cast...":this.ao[a].name};
E9.prototype.xf=function(a){g.UP.prototype.xf.call(this,a);this.I.setOption("remote","currentReceiver",this.ao[a]);this.Bb.Eb()};g.w(F9,g.fN);g.k=F9.prototype;
g.k.create=function(){var a=this.player.W(),b=g.lF(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:a.U("mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:a.U("enable_dial_short_lived_lounge_token"),enableCastLoungeToken:a.U("enable_cast_short_lived_lounge_token")};ETa(b,a);this.subscriptions.push(g.cv("yt-remote-before-disconnect",this.eT,this));this.subscriptions.push(g.cv("yt-remote-connection-change",this.NU,this));this.subscriptions.push(g.cv("yt-remote-receiver-availability-change",this.FL,
this));this.subscriptions.push(g.cv("yt-remote-auto-connect",this.LU,this));this.subscriptions.push(g.cv("yt-remote-receiver-resumed",this.KU,this));this.subscriptions.push(g.cv("mdx-privacy-popup-confirm",this.YV,this));this.subscriptions.push(g.cv("mdx-privacy-popup-cancel",this.XV,this));this.subscriptions.push(g.cv("mdx-manual-pairing-popup-ok",this.fS,this));this.FL()};
g.k.load=function(){this.player.cancelPlayback();g.fN.prototype.load.call(this);this.ci=new x9(this,this.player,this.Rb);var a=(a=ITa())?a.currentTime:0;var b=u9()?new P8(o9(),void 0):null;0==a&&b&&(a=L8(Q8(b)));0!==a&&this.Ob(a);NTa(this,this.pd,this.pd);this.player.Sk(6)};
g.k.unload=function(){this.player.Z("mdxautoplaycanceled");this.Vm=this.sj;g.vf(this.ci,this.Rb);this.Rb=this.ci=null;g.fN.prototype.unload.call(this);this.player.Sk(5);G9(this)};
g.k.ya=function(){g.dv(this.subscriptions);g.fN.prototype.ya.call(this)};
g.k.Kk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.ci.lj.apply(this.ci,[a].concat(g.v(c)))};
g.k.getAdState=function(){return this.mf};
g.k.Ck=function(){return this.Rb?Q8(this.Rb).Ck:!1};
g.k.hasNext=function(){return this.Rb?Q8(this.Rb).hasNext:!1};
g.k.Ob=function(a,b){this.sK=a||0;this.player.Z("progresssync",a,b);this.player.Oa("onVideoProgress",a)};
g.k.getCurrentTime=function(){return this.sK};
g.k.getProgressState=function(){var a=Q8(this.Rb),b=this.player.getVideoData();return{airingStart:0,airingEnd:0,allowSeeking:this.player.W().experiments.Ga("web_player_mdx_allow_seeking_change_killswitch")?this.player.kf():!a.isAdPlaying()&&this.player.kf(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.B+J8(a):a.B,isAtLiveHead:1>=(a.u?a.i+J8(a):a.i)-this.getCurrentTime(),loaded:a.N,seekableEnd:a.u?a.i+J8(a):a.i,
seekableStart:0<a.C?a.C+J8(a):a.C}};
g.k.nextVideo=function(){this.Rb&&this.Rb.nextVideo()};
g.k.Sz=function(){this.Rb&&this.Rb.Sz()};
g.k.eT=function(a){1===a&&(this.LE=this.Rb?Q8(this.Rb):null)};
g.k.NU=function(){var a=u9()?new P8(o9(),void 0):null;if(a){var b=this.Vm;this.loaded&&this.unload();this.Rb=a;this.LE=null;b.key!==this.sj.key&&(this.Vm=b,this.load())}else g.uf(this.Rb),this.Rb=null,this.loaded&&(this.unload(),(a=this.LE)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,L8(a)));this.player.Z("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.FL=function(){var a=[this.sj],b=a.concat,c=FTa();D8()&&g.Uz("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.ao=b.call(a,c);a=p9()||this.sj;H9(this,a);this.player.Oa("onMdxReceiversChange")};
g.k.LU=function(){var a=p9();H9(this,a)};
g.k.KU=function(){this.Vm=p9()};
g.k.YV=function(){this.pw=!0;G9(this);w9=!1;q9&&s9(q9,1);q9=null};
g.k.XV=function(){this.pw=!1;G9(this);H9(this,this.sj);this.Vm=this.sj;w9=!1;q9=null;this.player.playVideo()};
g.k.fS=function(){this.gz=!0;G9(this);g.Tz("yt-remote-manual-pairing-warning-shown",!0,2592E3);w9=!1;q9&&s9(q9,1);q9=null};
g.k.bf=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.ao;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?F8():H9(this,b)),this.loaded?this.Vm:this.sj;case "quickCast":return 2===this.ao.length&&"cast-selector-receiver"===this.ao[1].key?(b&&F8(),!0):!1}};
g.k.DF=function(){this.Rb.DF()};
g.k.Ki=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.eN("remote",F9);})(_yt_player);
